### ISSUE TITLE
Test for compatibility with ES6

### ISSUE THREAD

**Issue by scottinet** [kuzzleio/kuzzle#1003]
Elasticsearch v6 is out and we need to check if Kuzzle is compatible with it

**Comment by scottinet** [comment]
Quick answer: Kuzzle is not compatible with ES6 as it is, because now indexes can only hold one type.
We'll need to emulate data `collections` sooner than expected (or get rid of them entirely)

**Comment by Aschen** [comment]
See https://confluence.kaliop.net/pages/viewpage.action?pageId=35011846
