### ISSUE TITLE
The mapping for _kuzzle_info does not contain active and deletedAt for user/roles/profiles

### ISSUE THREAD

**Issue by dbengsch** [kuzzleio/kuzzle#1005]
Users, Profiles and Roles mappings defined in `lib/services/internalEngine/bootstrap.js` do not contain the fields `active` and `deletedAt` used in other parts of Kuzzle.

**Comment by benoitvidis** [comment]
Hum... The internal engine does not use _kuzzle_info at all. I removed it in https://github.com/kuzzleio/kuzzle/pull/1007.
