### ISSUE TITLE
It is impossible to use an ES script in document/update

### ISSUE THREAD

**Issue by dbengsch** [kuzzleio/kuzzle#1017]
The elasticsearch service forces the partial body to be included in a `doc` object in `lib/services/elasticsearch.js` in `update` method; it makes it impossible to use elasticsearch scripts to update documents.

**Comment by scottinet** [comment]
As discussed, this is not blocking, and allowing scripts is not something we want either, since it would allow users to create or delete documents through the update API, making rights management a mess.

**Comment by ballinette** [comment]
conclusion => we should not allow scripts in update method.
If a specific use case needs it, it should be performed by a plugin.
