### ISSUE TITLE
Support for HTTP verbs

### ISSUE THREAD

**Issue by ScreamZ** [kuzzleio/kuzzle#1018]
Hello,

I'm working on a project at work that would require to use the `PATCH` HTTP verb. But it seems not being possible. I have not checked for some common other verb but it can be nice to use all verbs of the spec.

https://developer.mozilla.org/fr/docs/HTTP/M%C3%A9thode/PATCH
https://tools.ietf.org/html/rfc5789

best regards

**Comment by ballinette** [comment]
Hi.
If I understand, you suggest to use `PATCH http://kuzzle:7512/index/collection/documentId` instead of `PUT http://kuzzle:7512/index/collection/documentId/_update`  ?

**Comment by ScreamZ** [comment]
I would like to define whatever HTTP verb I want in my custom plugin, no matter what i would like to do after that.

Currently using `patch` make the system crash.

**Comment by ballinette** [comment]
what do you mean about "the system crash" ?
You just get a 400 error ? or Kuzzle really crash and you need to restart it ?

**Comment by ScreamZ** [comment]
Using docker stack, PM2 is restarting kuzzle everytime, because the node script is crashing.
