### ISSUE TITLE
Promise functions not available if bluebird is not set in the prototype

### ISSUE THREAD

**Issue by Tyki** [kuzzleio/kuzzle#1023]
A member of your team told me that I had to do : 

```
import Kuzzle from 'kuzzle-sdk'
// Mandatory line
import bluebird from 'bluebird'

// Mandatory line
Kuzzle.prototype.bluebird = bluebird

const kuzzle = new Kuzzle(process.env.KUZZLE_HOST)
```

Otherwise, the promise functions are not available.

Example without changing the prototype of Kuzzle
`console.log(kuzzle.security)`
![image](https://user-images.githubusercontent.com/2605688/34651156-c3fb538e-f3cc-11e7-97ce-2cb2e09eb5d0.png)

After injecting Bluebird in the prototype : 
`console.log(kuzzle.security)`
![image](https://user-images.githubusercontent.com/2605688/34651178-092d2cc0-f3cd-11e7-9666-660490f513c2.png)

I didn't find anything in documentation about this (searching for "bluebird" in the search box)

Is that a normal behavior?

**Comment by scottinet** [comment]
Hi,

First and foremost, I discourage you from modifying Kuzzle's object prototype to include Bluebird, forcing the built SDK to promisify its exposed methods: this is an undocumented, internal feature, aimed to be used by the NodeJS SDK only.

As stated practically anywhere in our SDK documentation code examples, unfortunately, promises are only available on the NodeJS version of our SDK.

We wanted to add promisification on the browser-version for quite some time, but this is not as simple as you would think. First, native promises are an ES6 feature, and thus not as widely available as we need it to be for our SDK. Second, including a third-party library for promisification where another one might be used in a front project adds unnecessary download overhead costs. 

But this might change in the near future. Our next SDK major version includes many changes, one of them being the addition of a ES6 transpiler that may enable us to add somewhat native promises in our SDK at a minimum cost. This is something that we discussed internally, the only limiting factor right now is time, but this is definitely something that we'd like to do, including an additional constructor option letting SDK users to inject a Promise constructor, allowing them to use their favorite third-party promise library transparently.

For now though, I'm closing this ticket.
