### ISSUE TITLE
Admin profile security on user creation

### ISSUE THREAD

**Issue by fbrbovic** [kuzzleio/kuzzle#1035]
In the API or sdk when you are creating a user via security->createUser()
http://docs.kuzzle.io/sdk-reference/security/create-user/
it says that you can pass `profileIds`  to be assigned to the user and that's how you can set permissions.

Since this is available via JS SDK and accessible to everyone and that can't be trusted,
my question is then what is the best practice to secure the user creation and for example stop access to `admin` profileId being assigned by unauthorized requests ?

One of the ways I am thinking of is to create a plugin and listen to userCreate event and check at that time and stop admin profileid being assigned by unauthorized requests? 
Or is there also another way to secure this?

**Comment by fbrbovic** [comment]
K I think I've found an answer:

To allow only access to 
http://docs.kuzzle.io/api-documentation/controller-security/create-restricted-user/
and then set allowed profileids in configuration for the restricted user.

**Comment by ballinette** [comment]
Hi @fbrbovic 
You're right, `createUser` is a privileged method that must be allowed only to admin users (see [Role configuration](http://docs.kuzzle.io/guide/essentials/security/))
Note that with a fresh Kuzzle install, all actions are allowed to anonymous users by default (that let you try the product quickly), but you just have to create the first admin user (either with the [CLI](http://docs.kuzzle.io/guide/essentials/cli/#createfirstadmin) or using the [Backoffice](http://docs.kuzzle.io/guide/essentials/installing-backoffice/#create-an-admin-account)) to setup initial roles and restrict roles for users (by default, only `server/info` is allowed).

If you want to allow anonymous or non admin users to create new users with predefined profiles, you need to use `createRestrictedUser` method, indeed.
Note that this method will just ignore `profileIds` attribute from the request, and put instead the whole profiles from the `security.restrictedProfileIds` settings.

I mean: if you have this into your settings:
```javascript
security: {
 restrictedProfileIds: ['profile1', 'profile2', 'profile3']
}
```
, each user created with `createRestrictedUser` will be created with both profiles `profile1`, `profile2`, `profile3`.

Feel free to ask use for more clarifications about the product.

--
Gilles
