### ISSUE TITLE
Is it possible to limit fields returned for each action inside roles?

### ISSUE THREAD

**Issue by fbrbovic** [kuzzleio/kuzzle#1045]
Not sure if this is possible : To be able to configure roles to limit what document fields are returned per action ?
This is very useful to protect certain information in documents. 

I know we can write our own custom controller inside plugins and do it that way but having this capability in roles would remove a lot of need to write custom controllers.

**Comment by etrousset** [comment]
Hi,
 
this is currently not possible.

Regards

**Comment by fbrbovic** [comment]
Any plans to implement something like that?
