### ISSUE TITLE
WebSocket client seems to lose their subscriptions after being idle for a while

### ISSUE THREAD

**Issue by etrousset** [kuzzleio/kuzzle#1051]
After subscribing to a room, if the client just stay blocked on a recv() for a while, around 3~5 min, and a matching even occurs, then the client won't receive the notification.

This doesn't occur when receiving events regularly.

A work around if to do a websocket ping/pong every 60s when ideled

**Comment by Aschen** [comment]
I try to reproduce this bug with the JS SDK and a standalone python websocket client but I didn't succeed.  
I thought it was haproxy or nginx that close the idle connection but apparently not. (Kuzzle used `ws://iotboard.ams.kuzzle.io:7512`)

**Comment by scottinet** [comment]
@etrousset > can we close this issue?
