### ISSUE TITLE
Install script does not detect docker install failures

### ISSUE THREAD

**Issue by actifred** [kuzzleio/kuzzle#1052]
I tried to install kuzzle on an old Macbook.
It turns out that Docker is not supported on that machine (no support for MMU virtualization), but Kuzzle install script does not detect this failed attempt :

**[ℹ] Installing Docker...** 
```
Executing docker install script, commit: fc04d2c

Either your platform is not easily detectable or is not supported by this
installer script.
Please visit the following URL for more detailed installation instructions:

https://docs.docker.com/engine/installation/

```
**[✔] Docker successfully installed.**

then, if the user only reads the last line which is green (and I must confess that I first did so), the next steps is to install Docker Compose. Obviously that does not work neither. Unfortunately, the script does not detect the failure:

**Installing Docker Compose...** 
```
bash: line 303: /usr/local/bin/docker-compose: No such file or directory
chmod: /usr/local/bin/docker-compose: No such file or directory
```
 **[✔] Docker Compose successfully installed.**

This ends up with the script "checking that everything is running" and never ending.

Besides the error code checking, this particular issue is easy to prevent. Docker documentation helps us to detect the lack of virtualization support:
https://docs.docker.com/docker-for-mac/install/#what-to-know-before-you-install
As mentioned in this section, you can check that support on macOS using that command:
`sysctl kern.hv_support
`
Hope this helps, keep up the good job ! 👍

**Comment by jenow** [comment]
Hi @actifred! Thank you for your feed back. We are aware of this problem and we planned to redo this install script. Also thanks for the `sysctl kern.hv_support` hints :)
