### ISSUE TITLE
collection/updateMapping: the "properties" keyword should be removed

### ISSUE THREAD

**Issue by scottinet** [kuzzleio/kuzzle#1060]
Breaking change: this issue should only be implemented for a future new major version.

The current `collection/updateMapping` API route takes a body message of the following form:

```
{
  "properties": {
    "field1": {/* mapping */},
    "field2": {/* mapping */},
    "..."
  }
}
```

The `properties` layer seems superfluous and adds an unnecessary complexity to this route. It should be removed.

Internal backlog task: KZL-432

**Comment by scottinet** [comment]
Internal backlog task: https://jira.kaliop.net/browse/KZL-432

**Comment by Aschen** [comment]
Users can also update the `_meta` property for each collection (that's what we do for the form in the admin console) and we also support the `dynamic` property so we should keep the `properties` layer
