### ISSUE TITLE
We should be able to return a KuzzleRequest from a controller route

### ISSUE THREAD

**Issue by dbengsch** [kuzzleio/kuzzle#1085]
## Expected Behavior
As a plugin developer I would like to be able to return a KuzzleRequest as response of a controller route.

## Current Behavior
When returning a KuzzleRequest, it is used as result of the request and serialized as JSON, as a result, we get a POJO object only containing the requestId.

## Possible Solution
Detect the type of result and if it is a KuzzleRequest, use its error, status and result as error, status and result of the user request

## Steps to Reproduce
1. Create a custom controller with a route in a plugin
2. Return a KuzzleRequest (or a Promise resolving to a KuzzleRequest)
3. Call the route and inspect the result 

## Context (Environment)
docker image kuzzle/kuzzle:1.2.8

**Comment by Aschen** [comment]
https://jira.kaliop.net/browse/KZL-293
