### ISSUE TITLE
Login failed:  Cannot get roles for uninitialized profile anonymous

### ISSUE THREAD

**Issue by Tyki** [kuzzleio/kuzzle#1091]
Just installed Kuzzle 1.2.11 and on the first access to the backoffice, i'm creating an administrator and resetting anonymous rights

Note that this issue is not showing up in Kuzzle 1.2.6 (pre 1.2.7 with refactor of security controller)
## Expected Behavior

Be able to connect to backoffice

## Current Behavior

Login failed
## Possible Solution

Not resetting the anonymous rights

## Steps to Reproduce

1. Setup a new Kuzzle instance
2. Go to the Backoffice Kuzzle
3. Create an admin and check "reset anonymous rights"
4. Constat that it's impossible to connect with an admin account due to anonymous rights 

## Context (Environment)
Kuzzle 1.2.11, ES 5.4

**Comment by ballinette** [comment]
Confirmed.
Bug present since release 1.2.7
