### ISSUE TITLE
[PLugin context - Request constructor] input.headers from the base request are not propagated

### ISSUE THREAD

**Issue by ballinette** [kuzzleio/kuzzle#1107]
## Expected Behavior

In a plugin, we have an input request containing input headers.
We want to create and execute a derived request from this one, using pluginContext contructor:
```js
const derivedRequest = new context.constructors.Request(request, {
  controller: 'document',
  action: 'create',
  body: {
    document: 'content'
  }
});
```

The derivedRequest should contain the request's input header.

## Current Behavior
The input headers are not set.

## Possible Solution
fix [instantiateRequest](https://github.com/kuzzleio/kuzzle/blob/master/lib/api/core/plugins/pluginContext.js#L257) method in the pluginContext to inject input headers from the base request

## Steps to Reproduce
create a plugin with a custom controller/action, and configure an HTTP route to call it
add this code into the plugin's action:
```js
  const derivedRequest = new context.constructors.Request(request, {
    controller: 'server',
    action: 'now',
  });
  // show the headers from the base request:
  console.log('Base Request headers: ', request.input.headers)
  return context.accessors.execute(derivedRequest)
    .then(response => {
      // show the headers of the derived request:
      console.log('Derived Request headers: ', response.input.headers);
      return response;
    }
  })
``` 

Call the HTTP route with custom headers, for example 'X-Foo: Bar'.
The logs will show:
```
Base Request headers: { 'X-Foo': 'Bar' }
Derived Request headers: null
```

**Comment by scottinet** [comment]
As discussed, I think this is a bad idea to propagate protocol headers across newly instantiated requests that have nothing to do with said networks.
Among the several reasons I have against that issue, this would introduce a subtle and harmful side-effect for plugin developers branching actions depending on the presence of headers.

**Comment by scottinet** [comment]
@ballinette > can this be closed?
