### ISSUE TITLE
The security/searchUsers action does not support sorting and aggregations

### ISSUE THREAD

**Issue by dbengsch** [kuzzleio/kuzzle#1125]
## Expected Behavior
We should be able to specify aggs and sort parameters in the body of the search and get results sorted or aggregations

## Current Behavior
aggs and sort are not taken into account

## Steps to Reproduce
Call the action with aggs or sort in the body.

## Context (Environment)
Kuzzle 1.2.13

**Comment by Aschen** [comment]
Fixed by https://github.com/kuzzleio/kuzzle/pull/1144
