### ISSUE TITLE
Does not specify the right headers in Access-Control-Allow-Headers

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle#1135]
## Expected Behavior
Trying to execute a `kuzzle.index.exists('foo')` in the **browser**, which should at least trigger a request to Kuzzle.

## Current Behavior
I'm getting a `Request header field x-kuzzle-volatile is not allowed by Access-Control-Allow-Headers in preflight response.` error in the console.

## Possible Solution
It would be great that Kuzzle specifies the right allowed headers when asked by the `connect()` call. Currently, the only allowed headers are `Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With`.

## Steps to Reproduce
1. Load the 6.x Kuzzle SDK in a web page
2. call `connect()`
3. call any other method (my case was `kuzzle.index.exists('foo')`)

**Comment by scottinet** [comment]
:+1: 
Will be fixed by https://github.com/kuzzleio/kuzzle/pull/1134
