### ISSUE TITLE
Kuzzle stay silent on errors inside pipes

### ISSUE THREAD

**Issue by Tyki** [kuzzleio/kuzzle#1141]
I try to find where I can get the controller and action inside a pipe "http:get".

During the process, I tried to called "request.getController()" that is not a function but Kuzzle did not triggeered any error. I had to add a surround try/catch to know that my code failed 

## Expected Behavior

Kuzzle should tell the integrator that the function "request.fooBar()" is not a function from a pipe

## Current Behavior

Kuzzle remains silent

## Steps to Reproduce

1. Create a pipe 'http:get'
2. Inside the pipe, write 'console.log(request.foobar())'
3. Kuzzle is silent
4. Add a tryCatch and then we have our TypeError

## Context (Environment)

Kuzzle 1.3.1

**Comment by Aschen** [comment]
Unable to reproduce. Potentially linked (and fixed) by https://github.com/kuzzleio/kuzzle/pull/1143
(seen with @Tyki )
