### ISSUE TITLE
How to retrieve action/controller from a pipe?

### ISSUE THREAD

**Issue by Tyki** [kuzzleio/kuzzle#1142]
I want to know which controller/action is currently going on.

On the documentation, it says that the Request's parameters are inside the property "input" (https://docs.kuzzle.io/plugins-reference/plugins-context/constructors/#request)

Leading to a requestInput object.
On a requestInput, there are  "controller" and "action" attributes (https://github.com/kuzzleio/kuzzle-common-objects/blob/master/README.md#modelsrequestinput)

Am I right?

When I try to get these parameters from a "http:get" pipe, I have  the default value 'null' : 

Here is my code
```
this.onGetHTTP = (request, callback) => {
    try {
      console.log(request.input.action)
      console.log(request.input.controller)
    } catch (e) {
      console.log(e)
    }
  }
```

I also tried `request.input.getAction()` and `request.getAction()` without success.

Where are these data?

The console.dir(request.input, {depth: null}) show a poor object : 
```
RequestInput {
  args: 
  { requestId: '3eeaffae-f1f7-4688-a2db-3e9e4d16ae83',
    salon: 'foire_de_paris',
      sessionSalon: 'foire_de_paris_13969',
      language: 'fre-FR',
      fromThirdParty: 'platform' },
   resource: Resource {} }
```

## Context (Environment)

Kuzzle 1.3.1

**Comment by Aschen** [comment]
Fixed by https://github.com/kuzzleio/kuzzle/releases/tag/1.4.0
