### ISSUE TITLE
Websocket close unexpectely on to heavy payload

### ISSUE THREAD

**Issue by ScreamZ** [kuzzleio/kuzzle#1209]
I'm using `mUpdatePromise` through the Javascript SDK. I pushed too many documents within.

I probed that my connection was closed due to a too heavy payload, but without a message indicating this.
I figured it out because I reduced the amount of data sent and it worked.

## Expected Behavior

**Best solution** : I must get an error that explicitly explain why my WS was closed + documentation.
If you don't have the hand explicitly can we have something that tells something like `console.warn('Socket closed, this is maybe due to a too heavy payload sent through the network, see <link to doc about this>')` [here](https://github.com/kuzzleio/sdk-javascript/blob/70fa2660893e6d6e1ae4fa9a7ee86130a899507e/src/networkWrapper/wrappers/websocket.js#L49)

**Convenient solution** : Each methods likely to overload and make the request getting should display a disclaimer in the documentation indicating the reason.

----

I saw thanks to @Aschen that it might be related to 
`documentsWriteCount / maxRequestSize` config but nothing deals about it in the documentation.

Thanks you,
Regards

**Comment by Aschen** [comment]
Are you sure it's related to a heavy payload ? I have already sent payload of approximatively 20Mb each without problems (see https://github.com/kuzzleio/kuzzle-how-to/blob/master/massive-data-import/scripts/loadMCreate.js)

And Kuzzle tells you why your request is rejected when you send a too heavy payload

**Comment by ScreamZ** [comment]
Almost sure, we changed the size with @benoitvidis and it worked. He told me he knows it is a bit brutal reject.

The promise (or callback) for the « too heavy call » never reject (nor call the provided callback).

But we receive a message [here](https://github.com/kuzzleio/sdk-javascript/blob/70fa2660893e6d6e1ae4fa9a7ee86130a899507e/src/networkWrapper/wrappers/websocket.js#L49). I think there is a lack of type of message handled.

**Comment by alexandrebouthinon** [comment]
> I saw thanks to @Aschen that it might be related to
`documentsWriteCount / maxRequestSize` config but nothing deals about it in the documentation.

I close the issue

**Comment by ScreamZ** [comment]
@alexandrebouthinon is it updated ?
