### ISSUE TITLE
Suggestion: Add modularity to users collection

### ISSUE THREAD

**Issue by ScreamZ** [kuzzleio/kuzzle#1220]
# Add Modularity to users collection

Hello,
briefly I'm writing a feedback about an use case we are facing. If this could help for future customisation that could be nice for everybody.

**The problem**
We recently detected that we have a mapping issue on the kuzzle internal `users` collection, we have custom fields added, which is great because once we call `getMe` method we have the user with all its meta.

Instead of deprecating one field due to elastic search constraints in a matter of field, we would have preferred to create a new index and have the capability to specify this new index as the new source of truth for kuzzle. 

*I might be wrong but I think this is currently not available ?*

## My current workarounds

1. Deprecating a field and create a new one on the `users` collection.
2. Or using elasticsearch alias and use `users` as an alias for another collection (which is totally acceptable and clean).

## Possible Solution
1. We could consider adding a param in the kuzzle config defining the collection name.
2. We could document the alias solution in the documentation somewhere in a FAQ like topic.

What do you thing about it ?

Regards,
Andréas

**Comment by Aschen** [comment]
Hi @ScreamZ ,

I didn't think it's a good idea to allow developers to specify the index they want to use for internal `users`.  
Actually the users are stored in kuzzle internal index that is protected and restricted.

You can use the [security:updateUserMapping] route to specify the user mapping before adding new fields.

**Comment by stafyniaksacha** [comment]
Hi, I got the same architecture issue.
I can not know how my user data will evolve. 

The cleanest way I found is by creating a dedicated controller plugin.

**Comment by Aschen** [comment]
Hi @stafyniaksacha,

What is your exact need ?

**Comment by Aschen** [comment]
This has been done in Kuzzle v2.  
The name of the internal index is now part of Kuzzle configuration so you can change it
