### ISSUE TITLE
Is it possible to get notification using push notifications?

### ISSUE THREAD

**Issue by MohiuddinM** [kuzzleio/kuzzle#1226]

**Comment by Aschen** [comment]
Hi @MohiuddinM,
I didn't understand well your question, you mean native mobile push notifications ?

**Comment by MohiuddinM** [comment]
I have a mobile application and since keeping web socket connection open for long is not an option, how can my application get notified when there is a notification on the server

**Comment by Aschen** [comment]
You have to use the native notification module to have notifications without websocket.

**Comment by MohiuddinM** [comment]
Yes that is my question, how can I send a push notification to my mobile application from Kuzzle server

**Comment by Aschen** [comment]
I suppose that you are using Flutter am I wrong ?
I am not a Flutter expert but I know some guys from another has to use an external service like OneSignal, and I see that they have a Flutter SDK: https://github.com/OneSignal/OneSignal-Flutter-SDK

Another solution may to use this Flutter plugin: https://github.com/mitchhymel/local_notifications

**Comment by MohiuddinM** [comment]
Yes, I already know how to hook OneSignal etc. But, what I am asking for is how to hook OneSignal or FCM with Kuzzle?

**Comment by Aschen** [comment]
Hi @MohiuddinM,
Maybe you could come on Gitter to talk about this ? https://gitter.im/kuzzleio/kuzzle
It will be more convenient to resolve your issue, I will put the solution here after

**Comment by stafyniaksacha** [comment]
Did you have taked this article in consideration @MohiuddinM ? 
https://medium.com/flutter-io/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124

**Comment by Aschen** [comment]
Push notifications are not handled natively by Kuzzle. You have to use Apple native SDK or Android native SDK.
