### ISSUE TITLE
logs transport format "simple" in .kuzzlerc.sample

### ISSUE THREAD

**Issue by lethak** [kuzzleio/kuzzle#1228]
Hi,

I am trying to find the proper documentation regarding this option

https://github.com/kuzzleio/kuzzle/blob/5fe87e6d5c1f58af23fca784c5a23b871ea044a0/.kuzzlerc.sample#L294

It seems its not coming from winston
 https://github.com/winstonjs/winston/blob/master/docs/transports.md#console-transport

Is it a leftover/mistake, or I am missing something on my end ?
Thanks.

**Comment by benoitvidis** [comment]
Thank you @lethak . 
You are right, this option is not used and is a mistake. We'll remove it from the sample.
