### ISSUE TITLE
HTTP Endpoints: Add createFirstAdmin endpoint so no console or CLI is needed for that step

### ISSUE THREAD

**Issue by broken-bytes** [kuzzleio/kuzzle#1244]
Having the createFirstAdmin as an HTTP endpoint would help in situations where the CLI and admin console is not used and all you want is the HTTP API, thus is is inconsistent that the HTTP API lacks this feature

**Comment by Aschen** [comment]
Are you sure that the `security:createFirstAdmin` can not be accessed through HTTP ?
https://docs-v2.kuzzle.io/api/1/controller-security/create-first-admin/

**Comment by broken-bytes** [comment]
From the doc link you send me it seems possible, but the old guide does only mention the CLI and console, thus I didn't search for an HTTP call in the docs

**Comment by Aschen** [comment]
It is recommended to use the new version of the documentation, we rewrite the API and SDK parts and we just have to adapt some old snippets from the Guide and we will release the new version officialy

**Comment by Aschen** [comment]
New documentation version is officially released: https://docs.kuzzle.io/api/1/controller-security/create-first-admin/
