### ISSUE TITLE
Impossible to customize CORS allowed headers

### ISSUE THREAD

**Issue by dbengsch** [kuzzleio/kuzzle#1258]
For now, the "Access-Control-Allow-Headers" header returned by Kuzzle with the HTTP protocol can not be customised:
`'Access-Control-Allow-Headers': 'Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With, Content-Encoding, Content-Length, X-Kuzzle-Volatile'`
This behaviour could be enhanced by allowing to customise it via the configuration.

## Expected Behavior
Return custom headers with already mandatory ones in the "Access-Control-Allow-Headers" header

## Current Behavior
The header is forced with value`Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With, Content-Encoding, Content-Length, X-Kuzzle-Volatile`

## Possible Solution
A configuration entry in RC could be provided to allow its customisation. Default necessary headers should always be allowed as before.

## Steps to Reproduce
N/A

**Comment by alexandrebouthinon** [comment]
@dbengsch: #1259 merged on development branch waiting for next release.
