### ISSUE TITLE
createRestrictedUser is not a function

### ISSUE THREAD

**Issue by mehdweb34** [kuzzleio/kuzzle#1264]
Bonjour,
Je suis un nouvel utilisateur de Kuzzle (js).

J'essaie d'utiliser Kuzzle avec Angular 7, tout fonctionne très bien mais je bloque à une étape assez importante, la création d'un user anonyme, que j'essaie d'implémenter en suivant votre doc. **[Voir lien](https://docs.kuzzle.io/sdk-reference/js/5/security/create-restricted-user/)**

Mais, la fonction "kuzzle.security.createRestrictedUser" n'est pas reconnue.
Y'a t'il eu des changements récemment ?

Merci d'avance pour votre aide !
Ps : votre outil à l'air terrible :)

**Comment by alexandrebouthinon** [comment]
Salut @mehdweb, je pense que tu utilises l'ancienne version de notre SDK JavaScript. Essaie de modifier ton `package.json` pour utiliser la version 6.

**Comment by mehdweb34** [comment]
Merci pour ta réponse @alexandrebouthinon, après vérification j'utilise bien la v6.

La fonction "kuzzle.security.createRestrictedUser" a été supprimée dans cette version.
J'avais seulement à donner les bonnes permissions pour le rôle "anonymous" et à utiliser  "createUser" tout simplement :)

Merci à toi et à bientôt sûrement :p
