### ISSUE TITLE
Colleciton `_meta` data disappears on Kuzzle restart

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle#1268]
## Expected Behavior
Set a `_meta` field on a collection, restart and be able to see the `_meta` field.

## Current Behavior
The field has disappeared after the reload.

## Possible Solution
Could this be tied to the `indexCache`?

## Steps to Reproduce
See the Expected Behavior.

**Comment by Aschen** [comment]
https://github.com/kuzzleio/kuzzle/pull/1257
