### ISSUE TITLE
Unable to connect to kuzzle proxy server at "https://localhost:7512" [1006] 

### ISSUE THREAD

**Issue by cklinx** [kuzzleio/kuzzle#1285]
Hi, i am trying to connect with SSL to kuzzle but i use it i get this error.

Without works fine.

using http://console.kuzzle.io i get `Unable to connect to kuzzle proxy server at "https://localhost:7512" [1006] `

using node.js 
```
const options = {
    sslConnection: true
  }

  // Instantiates the websocket protocol
  const websocketProtocol = new WebSocket('localhost', options);

  // Use it with Kuzzle
  const kuzzle = new Kuzzle(websocketProtocol);
```
get this `Error: Client network socket disconnected before secure TLS connection was established
`

Any idea?

Thanks

**Comment by alexandrebouthinon** [comment]
Hi @cklinx, Kuzzle alone cannot act as SSL proxy. You need to configure a valid SSL proxy using Nginx or HaProx. Some Nginx documentation that could help you => https://docs.nginx.com/nginx/admin-guide/security-controls/securing-http-traffic-upstream/

**Comment by cklinx** [comment]
Hi @alexandrebouthinon , i make a SSL proxy, can you show me a nginx config file that allow ssl connection with kuzzle console and nodejs request? 

Thanks in advance.

**Comment by cklinx** [comment]
Solved, was a certificate problem.

This is  working script:
```
map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

upstream kuzzle {
  server kuzzle:7512;
  #server 127.0.0.1:7512/ws;
}

server {
    listen 80;

    server_name your.server.com;

    location / {
        return 301 https://$host$request_uri;
        #proxy_pass http://kuzzle;
    }
}

server {

    client_max_body_size 0;

    listen 443 ssl;
    listen 7511 ssl;

    server_name your.server.com;

    ssl_certificate /etc/letsencrypt/live/your.server.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/your.server.com/privkey.pem;

    #location / {
    #   proxy_pass https://kuzzle;
       #proxy_pass http://$request_uri;
    #}

    location / {
        proxy_pass http://kuzzle;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 99986400;
    }
}
```

**Comment by Aschen** [comment]
Thanks you for sharing your script @cklinx ! We are also currently working on an article on how to use Kuzzle with SSL.
