### ISSUE TITLE
Rename index or collection

### ISSUE THREAD

**Issue by cklinx** [kuzzleio/kuzzle#1287]
Is possible rename an index or collection?
I need to update my production data so i was thinking about:
 
- create a tmp index or collection (with updated data)

- delete the old data

- renane tmp with the production name

I cant find any docs about it.

Thanks in advance.

**Comment by etrousset** [comment]
Hi @cklinx,

indeed there is no way to rename a collection. This is a limitation in elasticsearch.
Your are right about the migration procedure, you'll have to create a new index with your new mappings and move your data from the old index/collection to the new one.

Regards

**Comment by cklinx** [comment]
Thanks @etrousset,

should i use bulk? cus i discover elasticsearch [_reindex](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html#docs-reindex).

Can you show a simple example please?

**Comment by Aschen** [comment]
hi @cklinx ,
Sorry for the long answer but a feature that allows to dump and restore indexes is almost done: https://github.com/kuzzleio/kuzzle/pull/1319

You can already use the new CLI actions from this PR to dump and restore your indexes.
