### ISSUE TITLE
Suggestion: using redis client-setname

### ISSUE THREAD

**Issue by lethak** [kuzzleio/kuzzle#1320]
Hi,

It is my understanding Kuzzle maintain a client connection to redis.

This is observable via [CLIENT LIST](https://redis.io/commands/client-list)
However, Kuzzle could use [CLIENT SETNAME](https://redis.io/commands/client-setname) in order to be easily identified.

Hardly an urgent need, but could be useful for monitoring and debug when the same redis instance is shared with multiple clients.

**Comment by scottinet** [comment]
Good idea, will be done. :+1:

**Comment by Aschen** [comment]
Tracked here: https://github.com/kuzzleio/kuzzle/issues/1655
