### ISSUE TITLE
Suggestion : Add strict mapping to users.

### ISSUE THREAD

**Issue by ScreamZ** [kuzzleio/kuzzle#1347]
As suggested below, this could be nice to add strict mapping to users collection.

<img width="426" alt="Screenshot 2019-07-10 at 10 48 43" src="https://user-images.githubusercontent.com/6640835/60955191-a2e8bd00-a300-11e9-8d8f-125f88b11237.png">

**Internal slack thread link**
https://kaliop.slack.com/archives/C1W3P0UKC/p1562680185067700

**Comment by Aschen** [comment]
Hi @ScreamZ !
It's a good idea, I added the feature to our product workshop, we will discuss it soon :)

**Comment by Aschen** [comment]
I just tested this and it's already working:
`curl -X PUT -H "Content-Type: application/json" -d '{"dynamic": "strict", "properties": { "name": {"type": "keyword"} } }' http://kuzzle:7512/users/_mapping`

However you cannot see it when you use `security:getUserMapping` but changing  the API return would introduce a breaking change so it's will be for Kuzzle v2 only
