### ISSUE TITLE
Kuzzle _mget break support for Service worker API

### ISSUE THREAD

**Issue by ScreamZ** [kuzzleio/kuzzle#1366]
Hello,

For an app context I would need to cache some response from my https://docs.kuzzle.io/core/1/api/controllers/document/m-get/ method, the thing is that currently this is using `POST` for a `GET` call.

I understand the concern of using POST for large payload, but I think this should rather rely on https://docs.kuzzle.io/core/1/api/controllers/document/search/ or external plugin for large payload. (Note: This also break search that is using GET)

```WorkboxError.mjs:33 Uncaught (in promise) attempt-to-cache-non-get-request: Unable to cache 'https://xxxx-pp.xxx.fr/yyyyyy-xxxxxx/cours/_mGet' because it is a 'POST' request and only 'GET' requests can be cached.```

Service worker Cache Storage API, cannot cache POST request.
https://w3c.github.io/ServiceWorker/#cache-put

There's a related discussion in the spec repository: https://github.com/slightlyoff/ServiceWorker/issues/693

There are workaround like this one but everybody is considering POST as a write call, not a read one : 

https://serviceworke.rs/request-deferrer.html Basically, the solution serializes requests to IndexedDB.

Could be nice to have some though for this issues, PWA are more and more adopted nowadays and this is true blocker.

Regards

**Comment by scottinet** [comment]
First, this is not a bug, but an intended design, so I'm changing the labels.

**Comment by scottinet** [comment]
Second: mGet is using POST because it can handle a very, very, very large number of documents to fetch in one time, which can very quickly break the limits on querystrings sizes, ending up in a HTTP 413 error, making that API action unusable.

But I guess that a possible solution is to make it work with the GET verb, and if it breaks because the querystring is too large, then clients can always fall back to a POST query.

**Comment by Aschen** [comment]
This feature has been approved in our product workshop.

User will be able to query the `document:mget` action with a list of ids either in the URL or in the request body.
