### ISSUE TITLE
Feature Request: Dynamic CORS configuration pattern

### ISSUE THREAD

**Issue by ScreamZ** [kuzzleio/kuzzle#1369]
Hello,

Currently we need to use CORS with a `.kuzzlerc` file and specify a string.

Sometimes you need to implement such pattern : https://stackoverflow.com/a/23998863/5320409

Can we imagine one way (or actually existing) way to deal with this ? (Plugin pipe would work ?) or should we rely on reverse proxy configuration ?

Regards

**PS:** CORS policies config are hidden in the doc https://github.com/kuzzleio/kuzzle/blob/master/.kuzzlerc.sample, even using algolia search, could be nice to add some reference, this is key feature and you'll probably have many questions on how to deal with it if it keep being hidden there. :)

**Comment by Aschen** [comment]
Hi @ScreamZ,

This kind of feature seems to be provided by reverse proxies such as Apache or Nginx.  
Your need seems to be very specific and I think it's better to implement it directly in a plugin using a pipe.
However, I will still suggest your proposal to our next product workshop.

Concerning the actual CORS documentation, you're right, we need to document this somewhere.
