### ISSUE TITLE
Unexpected crash on multipart / data

### ISSUE THREAD

**Issue by ScreamZ** [kuzzleio/kuzzle#1486]
See related thread on slack with private dump data

https://kaliop.slack.com/archives/C1W3P0UKC/p1570696077000100

**Comment by scottinet** [comment]
Hi @ScreamZ 

Did you find a way to reproduce the problem?

And if you did, does it still happen with kuzzle@1.11?

**Comment by scottinet** [comment]
Inactive issue.
