### ISSUE TITLE
securityController -- formatUserForSerialization and formatProfileForSerialization do not hydrate properly

### ISSUE THREAD

**Issue by ballinette** [kuzzleio/kuzzle#159]
I found something strange within securityController, in formatProfileForSerialization and formatUserForSerialization functions (see https://github.com/kuzzleio/kuzzle/blob/master/lib/api/controllers/securityController.js#L34 ):

if "hydrate" is true, the response will be overrided and all its additional attributes deleted.

Instead of,

    var formatUserForSerialization = function (user, hydrate) {
      if (hydrate) {
        return {
          _id: user._id,
          _source: {
            profile: formatProfileForSerialization(user.profile, true)
          }
        };
      }
      return user;
    };

we should have something like:

    var formatUserForSerialization = function (user, hydrate) {
      var response = { _id: user._id, _source: user }
      if (hydrate) {
        response._source.profile = formatProfileForSerialization(user.profile, true);
        };
      }
      delete response._source._id;
      return response;
    };

**Comment by ballinette** [comment]
Also, we should add a trigger within formatUserForSerialization() to let plugins change the user response data, for example remove the password if we user the auth-passport-local plugin

That means probably also that we need to promisify this function.

**Comment by AnthonySendra** [comment]
Ok, I take this one. I will update the PR #158

**Comment by AnthonySendra** [comment]
You're totally right !
I propose to merge the PR #158 without the fix and open a second PR in a next time, in order to have a quickly working SDK

**Comment by ballinette** [comment]
Yep, indeed, this bug was not introduced by your PR, so for me it makes perfect sense to fix it into a separate PR ;)
