### ISSUE TITLE
Either make custom errors description field optional or fix the documentation

### ISSUE THREAD

**Issue by benoitvidis** [kuzzleio/kuzzle#1603]
# Expected Behavior

The configuration sample given on https://docs.kuzzle.io/core/2/plugins/plugin-context/errors-manager/ should  work out of the box (BTW, the code in the sample at the bottom of this page seems incorrect too).

## Current Behavior

```
PluginImplementationError: [kuzzle-plugin-auth-passport-local] errors field in manifest.json badly formatted: Error configuration file : Field 'description' is required and must be a string (domain: 4, subdomain: 0, error: expired-password). 
```

## Possible Solution

I would personally remove all description fields from the API errors as this information does not seem to be used anywhere and, if it is, does not provide much added-value compared to the error message.

Alternatively, the documentation should be fixed.

**Comment by scottinet** [comment]
Description should remain mandatory for native errors as it allows us to auto-build our documentation pages. 

But I agree that this has no added value for plugins.  :+1:

**Comment by scottinet** [comment]
Fixed in the next Kuzzle version.
