### ISSUE TITLE
Upload files no longer works in Kuzzle v2

### ISSUE THREAD

**Issue by CrokNoks** [kuzzleio/kuzzle#1605]
## Expected Behavior
Form submission with content-type multipart/form-data and file attachments should work like it did in kuzzle v1

## Current Behavior
Kuzzle respond with a 400 Bad Request error and the following message : `Invalid request content-type. Expected "application/json", got: "multipart/form-data; boundary=----WebKitFormBoundaryXXXX`

## Steps to Reproduce
Try to send a file to a route in Kuzzle V2

## Context (Environment)
Kuzzle version: 2
Node.js version: 12
SDK version: 6.1.0 / 7.1.4
Common Object : 4.1.1

**Comment by Shiranuit** [comment]
This should be fixed by now, if somehow it's not feel free to open a new issue
