### ISSUE TITLE
bootstrap parsing all es indexes

### ISSUE THREAD

**Issue by Perfect-Web** [kuzzleio/kuzzle#1633]
## Expected Behavior
bootstrap and only test the kuzzle related indexes `kuzzle_services__storageEngine__internalIndex__name`

## Current Behavior
it reads and unserializes ALL the indexes present on elasticsearch which are not related to kuzzle

## Steps to Reproduce
pass env `kuzzle_services__storageEngine__internalIndex__name=kuzzle-core`
or anything different than the default index name
also set `DEBUG=*` to see it parsing other indexes

## Context (Environment)

Kuzzle version: >= 2.1
Node.js version:
SDK version:

**Comment by Aschen** [comment]
Hello @Perfect-Web ,

I tried to reproduce with setting a different internal index name as specified but I can't see anything related to another index than this one in the logs.

```
# In Kuzzle repository
$ WITHOUT_KUZZLE=true docker-compose up -d
# Wait...
$ DEBUG=kuzzle* kuzzle_services__storageEngine__internalIndex__name=kuzzle-core node bin/start-kuzzle-server
```

Also I created other ES indexes directly with curl and I can't see them in Kuzzle (which is the intended behavior).

Can you be more specific about your error and your intended behavior?

**Comment by Perfect-Web** [comment]
@Aschen set `DEBUG=*`

**Comment by Aschen** [comment]
I don't see the point of setting `DEBUG=*` because it will show debug of every packages and not only Kuzzle.

Also by looking at the complete log with `DEBUG=*`, I can't see any references to another index than the one I put in parameter
