### ISSUE TITLE
cannot pass onExistingUsers from cli

### ISSUE THREAD

**Issue by Perfect-Web** [kuzzleio/kuzzle#1634]
## Expected Behavior
existing param to pass `onExistingUsers` when loading fixtures thru cli

## Current Behavior
no way to specify the flag 

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

Kuzzle version:
Node.js version:
SDK version:

**Comment by Aschen** [comment]
Hi @Perfect-Web ,

You can pass arguments with the `--arg` or `-a` flag:
```
$ kourou sdk:query admin:loadSecurities -a onExistingUsers=skip
``` 

Please note that Github is only intended for bug and feature request and any technical question must be asked either to the community on [Discord](http://join.discord.kuzzle.io) or to the core team on [Stackoverflow](https://stackoverflow.com/search?q=kuzzle) with the `kuzzle` tag.
