### ISSUE TITLE
As an end user, I'd like to have a cluster more resilient to split

### ISSUE THREAD

**Issue by berthieresteban** [kuzzleio/kuzzle#1653]
The topology of a cluster is now stored in redis, in a SET, where each member is a node of the cluster.

When a node connects, it retrieves this information, and uses it to try to connect to the other nodes (auto-discovery).
If he cannot contact these nodes, he decides that the topology is obsolete, and recreates this SET by putting only himself in it.

If a new node is created during a network split, this poses problems as each new node reconfigures the entire cluster around it.

This strategy should be improved to be more resilient in the event of a split.

Possible idea: no longer store this information in a SET, but in keys (prefixed "cluster:discovery:") that have a short expiration time (e. g. 2 * heartbeat), and refresh them at each heartbeat. A new node that could not connect to the others could then decide to wait for these keys to expire if it cannot contact the cluster, and decide to shut down (or wait + regular logs and refuse new requests until it can contact the cluster)

**Comment by scottinet** [comment]
will be implemented directly within #1692
