### ISSUE TITLE
As an end user, I'd like to listen to generic document events with Koncorde filters

### ISSUE THREAD

**Issue by berthieresteban** [kuzzleio/kuzzle#1656]
The idea behind this new (sub-)feature is, in addition to the new events to be created in the main story, to use Koncorde to allow plugin developers to easily plug callbacks to only listen to document writes of interest.

Three new wrappers should be proposed in the plugin context, with the following signatures:
* onDocumentWrite(index, collection, filters, callback)
* onDocumentUpdate(index, collection, filters, callback)
* onDocumentDelete(index, collection, filters, callback)

Implementation example (open to debate):

```
function onDocumentWrite(index, collection, filters, callback) {
  // there should be only 1 koncorde instance dedicated to this usage in the plugin
  // context, and instantiated only if used, to prevent unnecessary overhead
  const id = this.koncorde.register(index, collection, filters);

  if (!this.write[id]) {
    this.write[id] = [callback];
  } else {
    this.write[id].push(callback);
  }
}
```

Whenever one of these helpers are invoked for the first time, this triggers a generic callback handler to be attached to its corresponding event. For instance, invoking "onDocumentWrite" for the 1st time would attach the following handler to the "storage:xxxWrite" event (this is just an implementation example):

```
_onDocumentWriteHandler(request) {
  const ids = this.koncorde.test(
    request.input.resources.index, 
    request.input.resources.collection, 
    request.input.body,
    request.input.resources._id);

  if (ids.length > 0) {
    for (const id of ids) {
      if (this.write[id]) {
        for (const callback of this.write[id]) {
          callback(request);
        }
      }
    }
  }
}
```

**Comment by Aschen** [comment]
Use realtime from embedded SDK
