### ISSUE TITLE
As an end user, I'd like to have my request timeout when internal request to service take too long

### ISSUE THREAD

**Issue by berthieresteban** [kuzzleio/kuzzle#1659]
Internal core modules makes requests to external services (ES and Redis), if the request take too long, the original request must be responded with an ExternalServiceError

Timeout for each services must be configurable

**Comment by Aschen** [comment]
Rajouter à kuzzle.ask

**Comment by Shiranuit** [comment]
Today it's very rare when requests to our external services do timeout, the Javascript SDK do support adding a timeout to a request to avoid waiting too long.
