### ISSUE TITLE
As an end user, I'd like to know when I'm using a deprecated feature

### ISSUE THREAD

**Issue by berthieresteban** [kuzzleio/kuzzle#1661]
We should notify users (in development) when they are using obsolete features.

Controllers should checks for deprecation (method, parameters, etc)

Each deprecation is then added to an array returned with the response.

This array contain deprecation objects with a message and a version

SDK should then be able to print deprecation warning

https://trello.com/c/JHelN9Fa/216-adm-deprecation-module

**Comment by rolljee** [comment]
- [ ] https://docs.kuzzle.io/sdk/android/3/essentials/realtime-notifications/
- [ ] https://docs.kuzzle.io/sdk/js/7/protocols/http/properties/
- [ ] https://docs.kuzzle.io/sdk/js/7/controllers/collection/update/
- [ ] https://docs.kuzzle.io/sdk/js/7/controllers/collection/create/

- [ ] https://docs.kuzzle.io/core/1/plugins/plugin-context/constructors/dsl/
- [ ] https://docs.kuzzle.io/core/2/plugins/plugin-context/errors/parseerror/
- [ ] https://docs.kuzzle.io/core/1/plugins/guides/manual-setup/prerequisites/
- [ ] https://docs.kuzzle.io/core/2/plugins/plugin-context/constructors/request/
- [ ] https://docs.kuzzle.io/core/2/plugins/guides/pipes/
- [ ] https://docs.kuzzle.io/core/2/plugins/guides/events/core-kuzzle-start/

- [ ] https://docs.kuzzle.io/core/2/guides/cookbooks/realtime-api/terms/


- [ ] https://docs.kuzzle.io/core/2/protocols/api/context/errors/
- [ ] https://docs.kuzzle.io/core/1/protocols/api/context/errors/
- [ ] https://docs.kuzzle.io/core/2/protocols/api/context/request/
- [ ] https://docs.kuzzle.io/core/1/protocols/api/context/request/ 


- [x] https://docs.kuzzle.io/core/2/api/controllers/auth/update-self/
- [x] https://docs.kuzzle.io/core/2/api/controllers/auth/credentials-exists/
- [x] https://docs.kuzzle.io/core/2/api/controllers/collection/update-mapping/
- [x] https://docs.kuzzle.io/core/2/api/controllers/auth/update-my-credentials/
- [x] https://docs.kuzzle.io/core/2/api/controllers/auth/get-my-rights/
