### ISSUE TITLE
As an end user, I'd like to be able to load Vault encrypted file for securities

### ISSUE THREAD

**Issue by berthieresteban** [kuzzleio/kuzzle#1665]
Securities definition file should be stored encrypted with Kuzzle Vault since it can contain sensitive information like user password.

When loaded with the CLI or with the API, users should be able to specify an option to indicate if the securities file is encrypted or not.

Or even better, Kuzzle should be able to know if a credentials has been encrypted or not so everything can remain transparent for the user.

 

https://trello.com/c/S1ELTzVY/165-seb-donner-la-possibilit%C3%A9-que-le-fichier-charg%C3%A9-par-adminloadsecurities-soit-chiffr%C3%A9-par-le-vault

**Comment by xbill82** [comment]
We close this issue because the practice of creating users on startup is no more supported. Users that rely on the `--securities` startup option must migrate their process and use kourou to create users after deploy.
