### ISSUE TITLE
securityController -- searchProfiles/Users/Roles - total is never greater than from/size parameters

### ISSUE THREAD

**Issue by stafyniaksacha** [kuzzleio/kuzzle#167]
I have found something strange : the `total` returned by a search query isn't matching the total of items indexed in the search layer.
It will never be greater than the `size` parameter (if we send one, but by default, this parameter is set to 20 in `Repository.prototype.search`)

I haven't checked if this issue came from `Repository` or from `ReadEngine`

**Comment by AnthonySendra** [comment]
The problem come from `SecurityController`.

```js
return new ResponseObject(requestObject, {hits: users, total: users.length});
```

This is a bad copy/past from statistics where we have to calculate mannualy the total.
But the problem here, it's in this line of code, we don't know really how many users math the filter.

I takte this issue.
