### ISSUE TITLE
New real-time sync strategy for kuzzle cluster

### ISSUE THREAD

**Issue by berthieresteban** [kuzzleio/kuzzle#1671]
Pre-requisite: https://jira.kaliop.net/browse/KZL-1421

Implement the new real-time sync strategy by building a Koncorde cluster independant from (yet included in) Kuzzle core.

The new strategy to implement is detailed in the following confluence document: https://confluence.kaliop.net/display/LABS/2019-12-05+Cluster+evolutions

For future reference, here is also the slack debriefing: https://kaliop.slack.com/archives/GBJ9VRA01/p1575564826027000

**Comment by Aschen** [comment]
Done in 2.11.0 release
