### ISSUE TITLE
As a plugin developer, I'd like to have a new API to define controllers

### ISSUE THREAD

**Issue by berthieresteban** [kuzzleio/kuzzle#1679]
New API de declare plugin controllers and routes.

We have to keep the current system ({{this.controllers}} and {{this.routes}} as-is to avoid breaking changes.

The new system should use declarations made inside {{this.api}} :

```
this.api = {
  controllerFoo:  {
    actionBar: {
      fn: <function>,
      http: { verb: "", url: ""}
    }
  }
};
```

API routes created using that new form wouldn't be prefixed by the plugin name.

https://trello.com/c/VFUo9p5b/228-seb-get-rid-of-prefixes-for-api-routes-created-by-plugins

**Comment by Aschen** [comment]
Included in Kaaf
