### ISSUE TITLE
As an end user, I'd like to authenticate Kuzzle to my ES instance with xpack

### ISSUE THREAD

**Issue by berthieresteban** [kuzzleio/kuzzle#1684]
Allow to use an ES cluster with xpack authentication enabled

The configuration should allow Kuzzle to authenticate to ES.
The password should be stored in the vault or in an environment variable

https://trello.com/c/9QSyx4DG/255-seb-permettre-%C3%A0-kuzzle-de-sauthentifier-aupr%C3%A8s-de-es

**Comment by Aschen** [comment]
It's already possible
