### ISSUE TITLE
Use one const keyword per variable declaration

### ISSUE THREAD

**Issue by berthieresteban** [kuzzleio/kuzzle#1691]
Use this eslint rule: https://eslint.org/docs/rules/one-var

Auto fix existing files

https://trello.com/c/Wm0BUqw7/224-nrb-d%C3%A9claration-de-variable-eslint

**Comment by Leodau** [comment]
"one-var": [2, "never"]

**Comment by Aschen** [comment]
We are doing this incrementally.

Actually I tried to auto-fix this with the eslint rule but it messed up the declaration of module at the top of the files
