### ISSUE TITLE
security:searchUsers -> total property is wrong

### ISSUE THREAD

**Issue by berthieresteban** [kuzzleio/kuzzle#1709]
## Expected Behavior
Bug found [here](https://github.com/kuzzleio/kuzzle-admin-console/issues/767)
Using the [security:searchUsers](https://docs.kuzzle.io/core/2/api/controllers/security/search-users/) method, the `total` property of the result should be the real total number of users

## Current Behavior
Actually, the `total` property has the same value as the `fetched` property (which takes into account the query and the pagination)

## Possible Solution
Set the total value to real number of users without taking into account the query.

## Steps to Reproduce
1. Run kuzzle
2. Create an user
3. security:searchUsers (from=1, size=10) -> total=0 / fetched = 0
4. It should be total=1 / fetched = 0

**Comment by scottinet** [comment]
will be fixed in kuzzle 2.3.3
