### ISSUE TITLE
Cannot create a mapping with dynamic set to false

### ISSUE THREAD

**Issue by benoitvidis** [kuzzleio/kuzzle#1743]
Observed on 1.x but looking at the code, most likely still is the case on v2.

cf https://github.com/kuzzleio/kuzzle/blob/master/lib/service/storage/elasticsearch.js#L944
As long as the common mapping is set to allow dynamic mapping, users cannot create a non-dynamic one.

**Comment by Aschen** [comment]
You can create a collection with `dynamic` property to `false` by passing the argument as a string instead of a boolean.
The doc is unclear about whether the argument is a boolean or a string that's true.

**Comment by benoitvidis** [comment]
Thanks @Aschen , this works.
Still, besided updating the documentation, I believe Kuzzle should accept regular boolean values for this. Wrapping a boolean value in a string is very unnatural to me.

**Comment by Aschen** [comment]
@benoitvidis Yes to me too so you can pass either string or boolean and they will be converted to string before being sent to ES :+1:

**Comment by scottinet** [comment]
Will be released in the next non-hotfix version of kuzzle
