### ISSUE TITLE
Allow anonymous user to create account with auth:signup

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle#1776]
## Feature description

When anonymous users want to create an account into Kuzzle they must use the `security:createRestrictedUser` action.  

Instead of having this action in the `security` controller, we should have an action in the `auth` controller.

We need to add a `auth:signup` action who is more intuitive and deprecate the `security:createRestrictedUser` action

**Comment by Aschen** [comment]
Potential conflict with https://github.com/kuzzleio/kuzzle/pull/2016

**Comment by GuinierRemi** [comment]
Restart from what was done : assessment & do-over if needed.
