### ISSUE TITLE
Add bulk:updateByQuery

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle#1777]
## Feature description

Add a new action to the bulk controller to update documents without the Kuzzle limits.  

This action will use directly Elasticsearch [update_by_query](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html) capabilities

**Comment by sanskar-p** [comment]
Hi @Aschen @scottinet
I'd like to try my hands on this issue and get familiar with the codebase. I would be very grateful if you could advise me on what exactly I have to do.

**Comment by scottinet** [comment]
That would be awesome!
But right now is the worst time to work on that particular issue. See, I'm in the process of loosely coupling everything related to data storage, so there is a major refactor in the work (https://github.com/kuzzleio/kuzzle/tree/loose-coupling-storage).

If you could wait a bit, or start from my refactor branch, then the modifications should be fairly straightforward: 
* implement a bulk "updateByQuery" method in the ES service (different from the existing one used by `document:updateByQuery` obviously)
* add a new event in the client adapter (https://github.com/kuzzleio/kuzzle/blob/loose-coupling-storage/lib/core/storage/clientAdapter.js#L304). That event name could be `core:store:<scope>:document:bulkUpdate` (left to debate, if you find a better name go for it)
* add a new action in the bulk controller (https://github.com/kuzzleio/kuzzle/blob/loose-coupling-storage/lib/api/controller/bulk.js)
  * parse the API request using the controller's helpers (https://github.com/kuzzleio/kuzzle/blob/loose-coupling-storage/lib/api/controller/base.js)
  * invoke your new event with the appropriate arguments, using `kuzzle.ask`
* write unit & functional tests for the new feature

The storage refactor is nearly finished, I'm in the process of migrating existing unit tests (functional tests pass)
