### ISSUE TITLE
Allow to send custom Content-Type in custom routes

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle#1778]
## Feature description

Currently Kuzzle only supports application/json and multipart/form-data as input Content-Type for HTTP routes.

We need to allow developers to send custom Content-Type to HTTP routes.  
Then it's developers responsibility to parse the raw body and use it.

## Example usecase

A developer may want to send a CSV file in the body as text or a binary file.

## Possible solution (optional)

Add an option in the route declaration object to indicate that the content type will be different from json or multipart so Kuzzle will not try to parse it.

```
// in kaaf
app.controller.register('files', {
  actions: {
    csv: {
      handler: async request => console.log(request.input),
      http: [
        { verb: 'post', path: '/csv', raw: true }
      ]
    },
  }
});

// in plugins
this.routes = [
 { controller: 'files', action: 'csv', path: '/csv', verb: 'post', raw: true }
]
```

**Comment by Shiranuit** [comment]
This is now possible using the `protocol:http:beforeParsingPayload` starting from [Kuzzle 2.19.11](https://github.com/kuzzleio/kuzzle/releases/tag/2.19.11)
