### ISSUE TITLE
Better error messages when too many logins are submitted

### ISSUE THREAD

**Issue by scottinet** [kuzzleio/kuzzle#1781]
# Description

Kuzzle features a rate limiter, for any API route OTHER THAN `auth:login`: that particular route is managed separately to prevent spams by anonymous users to disable user logins, which would allow authenticated users to benefit from dedicated rate limiters.

The `auth:login` limit per second is handled by the `limits.loginsPerSecond` rc configuration, and is applied per second and per unique network connection.

When the login limit is reached, a standard "too many requests" error is sent back to the client, which can be misleading: since it's handled separately, this error leads customers to think that the problem lies within the rate limiters, which is not the case.

To prevent this, we need a dedicated "too many logins" error (which would still be a HTTP 429 error), to make things clearer for our users.

## Possible implementation

Adds a new error in [2-api.json](https://github.com/kuzzleio/kuzzle/blob/master/lib/kerror/codes/2-api.json#L120)

Throw the error in the [funnel](https://github.com/kuzzleio/kuzzle/blob/master/lib/api/funnel.js#L268) when there is too many login attempt

**Comment by sagarmulchandani** [comment]
Hi @scottinet  have made the change as per the requirements mentioned above. You can review the changes in the [PR](https://github.com/kuzzleio/kuzzle/pull/1837). Do let me know if any additional changes are required upon review.

_This PR is part of my contribution towards Hacktoberfest. If upon review it is legible please do add hacktoberfest-accepted label to it. Thank you :)_
