### ISSUE TITLE
Timezone support

### ISSUE THREAD

**Issue by Leodau** [kuzzleio/kuzzle#1795]
## Feature description
UTC in _kuzzle_info for timezone support

## Possible solution

- Add an option in the **kuzzlerc** to store the required timezone.
- Add the timezone in Kuzzle **server:info**

**Comment by scottinet** [comment]
Hm... This is a tricky one. I have a myriad of ideas, suggestions, and rebuttals, all at once, about that one.

For now, _kuzzle_info timestamps are in UTC, and it should be fairly easy for clients to interpret that information on their side.

Is there a use case for this feature request?

**Comment by Leodau** [comment]
Upon further consideration, making sure Kuzzle stores dates in UTC as default is kindda of a breaking change.

**Comment by Aschen** [comment]
Following @scottinet , aren't they already in UTC ?

**Comment by xbill82** [comment]
I also thought they already were in UTC.
