### ISSUE TITLE
Token expired event on persistent connections.

### ISSUE THREAD

**Issue by Leodau** [kuzzleio/kuzzle#1805]
## Feature description
At the moment, kuzzle only sends this event when a **real time** subscription is open.

## Possible solution
Given that kuzzle knows exactly when each token expires, don't wait for the user to make a request to respond with an error but if we have a persistent connection, just send back the event when the token expire.

**Comment by Aschen** [comment]
Duplicate https://github.com/kuzzleio/kuzzle/issues/2025
