### ISSUE TITLE
Smøl UI details to fix

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle#1840]
Links in warning blocks are rose on rose.
![image](https://user-images.githubusercontent.com/5023426/97274946-99f16700-1835-11eb-854c-6b2c2c0cfc4d.png)

Inline code is bigger than line-height: sometimes it overlaps.
![image (1)](https://user-images.githubusercontent.com/5023426/97275000-ad9ccd80-1835-11eb-828b-4dbb88d74666.png)

Tables don't fill the width of the card container.
![image (2)](https://user-images.githubusercontent.com/5023426/97275102-cefdb980-1835-11eb-97c0-807fe6947a1a.png)

Code blocks have unequal vertical padding.
![image (3)](https://user-images.githubusercontent.com/5023426/97275166-e177f300-1835-11eb-8ec9-2c2fc81b83c4.png)

**Comment by Njuelle** [comment]
wrong repos, moved here https://github.com/kuzzleio/documentation/issues/487
