### ISSUE TITLE
Improve server:healthCheck route

### ISSUE THREAD

**Issue by alexandrebouthinon** [kuzzleio/kuzzle#1871]
Currently [the health of a Kuzzle node is only defined from those of Redis and Elasticsearch](see: https://docs.kuzzle.io/core/2/api/controllers/server/health-check/#response))

That's not enough to allow a fairly accurate load balancing based on this route. To do so, you would have to query the Kuzzle stats module to get the number of requests processed (mainly for the HTTP protocol) but also the name of persistent connections for the WebSocket and MQTT protocols.

So from this data, it would be possible to configure thresholds (perhaps via the kuzzlerc) and modify the health of the node according to the exceedances or not of these thresholds.

**Comment by Aschen** [comment]
Duplicate of https://github.com/kuzzleio/kuzzle/issues/1872 ?

**Comment by alexandrebouthinon** [comment]
Yes Github glitched during issue creation, I close this one in favor of #1872
