### ISSUE TITLE
Add a document:createOrUpdate route

### ISSUE THREAD

**Issue by scottinet** [kuzzleio/kuzzle#1895]
# Document

Now this one is a bit counterintuitive. Until now, there weren't use cases for an upsert API route. Because document updates apply partial content modification to documents, it's normally not something we want to create a new document on the fly with only partial content.

However, here is a use case coming from one of our clients, which to me seems to justify the addition of that new route to Kuzzle:

> Well, we have a use case where we want to maintain a list of recommendations for a user. Those reccomendations come from different sources from a kafka topic.
>
> So when a recommendation is received we want to add it to the document for that user in our recommendations collection.
> If the customer is new, the document which matches the customer id will not exist yet. So we want to update the document by changing a specific set of recommendations OR create a new document with that user id and add the recommendation type.
We don;t really want a collection per rec type, because that means millions of documents in each of those collections.

In that specific case, it is desirable to add partial content to a document, or to create a new one on the fly if needed.

**Comment by robkane1** [comment]
Thanks for adding this feature request. Just to add to this...

Without this feature, options are:

A: Call `exists`, wait for a response, then based on the response, call either `create` or `update`. 
- too noisy 
- creates a lot of synchronous traffic when we will potentially have spikes of >1m messages in an hour
- risk of triggering unnecessary rebalancing.

B: Aggregate our messages into a ktable and fire the compiled result of that into the kuzzle collection.
- makes recovery from a kuzzle failure easier
- creates an unnecessary storage and memory overhead 
- message schema does't really suit a RDB - more suited to nosql
- overhead of creating external custom state store that operate across the consumer group
- replicating what we already have in kuzzle.

Given that kuzzle supports dynamic fields on documents and elasticsearch provides `upsert` functionality, seems reasonable to have this available in kuzzle. 

Equivalent ES:
```
POST test/_update/1
{
  "doc": {
    "name": "new_name"
  },
  "doc_as_upsert": true
}
```
