### ISSUE TITLE
[question] SSL/TLS support for MQTT?

### ISSUE THREAD

**Issue by meshle** [kuzzleio/kuzzle#1921]
Aedes is used for MQTT which supports TLS/SLL but I don't see any configuration options for that in Kuzzle config file, only port 1883. Is there a way to setup tls connection via mqtt with kuzzle?

**Comment by alexandrebouthinon** [comment]
Hi @meshle , indeed the SSL/TLS management is not handled inside of Kuzzle. This is intended to avoid having to manage internally such a complex brick subject to potential vulnerabilities.
But don't worry, you can still use an SSL proxy to fulfill this role:
- If you use containers (with Kubernetes or not), I can recommend [Traefik](https://doc.traefik.io/traefik/). All you need to do is use a [TCP router and configure a TLS certificate](https://doc.traefik.io/traefik/routing/providers/docker/#tcp).
- If you don't use containers, NGINX or HAProxy will do the trick. 

I hope I was able to help you as much as I could.

Cheers
