### ISSUE TITLE
Unable to create a document with auto-generated ID

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle#1923]
## Expected Behavior
Being able to create a document without specifying the ID, with the URL `http://kuzzle:7512/<index>/<collection>/_create`

## Current Behavior
Receiving the `Missing parameter "_id".` error.

## Context (Environment)

Kuzzle version: 2.8.0

**Comment by Aschen** [comment]
I just tried with CURL and I can't reproduce the error:
```
kourou collection:create foo bar

curl -X POST -H 'Content-Type: application/json' --data '{"age": 42}' http://localhost:7512/foo/bar/_create
```
