### ISSUE TITLE
[bug] resetSecurity doesn't work on role and searchRole doesn't return the good role content

### ISSUE THREAD

**Issue by berthieresteban** [kuzzleio/kuzzle#1939]
## Expected Behavior
After a resetSecurity, expect anonymous role to be reseted
AND searchRoles should return the good roles content

## Current Behavior
Updating role anonymous to 
```
{
  "controllers": {
    "*": {
      "actions": {
        "*": true
      }
    },
    "index": {
      "actions": {
        "list": false
      }
    }
  }
}
```
and then resetSecurity -> the anonymous role still contains index.list false
Also, searchRole doesn't return the good role content
It return the anonymous role like following snippet (withtout index.list false):
```
{
  "controllers": {
    "*": {
      "actions": {
        "*": true
      }
    }
}
```

## Context (Environment)
Kuzzle version: 1

**Comment by rolljee** [comment]
I think this should be split into 2 separate issues wdyt ?

**Comment by Aschen** [comment]
IMHO we are not going to fix this since Kuzzle v1 EOL is in 3 months.

**Comment by Shiranuit** [comment]
Since we reached the Kuzzle V1 End Of Life, we wont fix this issue.
