### ISSUE TITLE
Allow "inner_hits" key in Elasticsearch search body whitelist

### ISSUE THREAD

**Issue by Yoann-Abbes** [kuzzleio/kuzzle#1956]
Add the [inner_hits](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/inner-hits.html) ES key for nested query inside our [whitelist](https://github.com/kuzzleio/kuzzle/blob/master/lib/service/storage/elasticsearch.js#L105)

**Comment by Aschen** [comment]
This feature is only available since Elasticsearch 7.10 and for now we officially support Elasticsearch 7.4.

**Comment by MathieuVeber** [comment]
According to the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-request-inner-hits.html) it seems like this feature was available in version 6.8 😅
