### ISSUE TITLE
Export Kuzzle TS types to external package

### ISSUE THREAD

**Issue by alexandrebouthinon** [kuzzleio/kuzzle#2000]
To improve the developers experience when developing the KaaF plugin, we need to export the Kuzzle TS types (directory `/lib/types`) as an external NPM package like `@types/kuzzle`. This way we won't need to import the whole package of `kuzzle` to access it.

**Comment by ScreamZ** [comment]
@alexandrebouthinon Or you can just keep it that way and use https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export
