### ISSUE TITLE
Update Kuzzle Users form ES

### ISSUE THREAD

**Issue by foralobo** [kuzzleio/kuzzle#2038]
## Expected Behavior

When I execute a massive update to users from ES Api (_update_by_query), data must be updated

## Current Behavior

The data seems up to date but in reality it is not

## Steps to Reproduce

1. I Create un user in the kuzzle console
2. Call API _update_by_query from ES, it works but...
3. until I don't modify the content of user manually. 
4. If I do it, when I again call the api from ES, api respond with success
5. Go to console, users section
6. If I expand data user in table, there are the updated data from ES... but...
7. when I go to Edit User (icon) -> Custom, the data is one I had manually updated and it will not change more until I change data from this section.
8. In every case, if I call getCurrentUser () API, I get data inserted manually end not the one updated from ES

## Context (Environment)

Kuzzle version: (I am in testing with get started docker app) 2.10.4
Node.js version: (I am in testing with get started docker app) v12.18.1
SDK version: JS SDK v. (but is not a problem of SDK)

**Comment by Aschen** [comment]
Hi @foralobo ,

Kuzzle simply query ES to get the user documents so if you modify them with an ES query Kuzzle will then use the modified documents.

Can you show your ES query so I can try to reproduce?

**Comment by foralobo** [comment]
Of course,


`POST /%%kuzzle.users/_update_by_query
{

  "script": {
    "source": "ctx._source.forasChat = params.forasChat",
    "params": {
      "forasChat": {
      
      "settings": {
        "blocked": {
          "list": []
        },
        "online": {
          "all": true,
          "exceptions": []
        }
        
      }
      }
    }
  }
}`


I use kibana to execute this script... and this is result of my query!!

<img width="407" alt="Schermata 2021-04-06 alle 14 01 17" src="https://user-images.githubusercontent.com/11678983/113707878-d082b600-96e0-11eb-8235-ac9ea157b23c.png">


Then I fo to console:

end expand my user "pippo":

<img width="387" alt="Schermata 2021-04-06 alle 14 01 49" src="https://user-images.githubusercontent.com/11678983/113707988-fc9e3700-96e0-11eb-9ac8-1208a31fac02.png">

It's correct!!

but when I go to manual update of my user "pippo":

<img width="1004" alt="Schermata 2021-04-06 alle 14 02 00" src="https://user-images.githubusercontent.com/11678983/113708164-2eaf9900-96e1-11eb-8a4a-f7e9f7ad9846.png">


**_IMPORTANT_**: this is because I, before execute query, had edited manually content of "pippo" from console.

**Comment by Aschen** [comment]
I tried to reproduce but I have the expected behavior:

```
curl -X POST -H  "Content-Type: application/json" "localhost:9200/%%kuzzle.users/_update_by_query" --data '{

  "script": {
    "source": "ctx._source.forasChat = params.forasChat",
    "params": {
      "forasChat": {

      "settings": {
        "blocked": {
          "list": []
        },
        "online": {
          "all": true,
          "exceptions": []
        }

      }
      }
    }
  }
```

![image](https://user-images.githubusercontent.com/4447392/113712252-302f9000-96e6-11eb-8264-0d7aaee3c6f9.png)

![image](https://user-images.githubusercontent.com/4447392/113712277-39206180-96e6-11eb-82d2-a2e276cfaef9.png)

If you reload the admin console?

**Comment by foralobo** [comment]
Are you try to edit From console the content of user and then.. re-execute the query?

**Comment by foralobo** [comment]
> Did you try to reload the admin console?

Yes I try to reload console and also the server. But no changes happen!! :(

**Comment by Aschen** [comment]
Ok I found the problem.

Kuzzle cache users content in Redis to avoid a request to the database when it comes to load the `profileIds` field who contain the information needed by the permission system.

You need to reset the internal cache after your query to Elasticsearch, you can use the [admin:resetCache](https://docs.kuzzle.io/core/2/api/controllers/admin/reset-cache) action.

Example with Kourou:
```
kourou admin:resetCache -a database=internalCache
```

**Comment by foralobo** [comment]
Great!!!! It Works.... thank you very much
