### ISSUE TITLE
Event "core:realtime:user:subscribe:after" not triggered in plugin hooks

### ISSUE THREAD

**Issue by screwt** [kuzzleio/kuzzle#2090]
## Expected Behavior
Hook on "core:realtime:user:subscribe:after" should trigger the function.

## Current Behavior
Hook on "core:realtime:user:subscribe:after" does not trigger the function

## Steps to Reproduce
```typescript
import { Plugin } from 'kuzzle';

export class SimplePlugin extends Plugin {
    constructor() {
        super({ kuzzleVersion: '>=2.8 <3' });

        this.hooks = {
            'core:realtime:user:subscribe:after': async (roomId)=>{
                console.log("core:realtime:user:subscribe:after")
            }
        }
    }
    
    init(customConfig, context) {}
}

```

## Context (Environment)
Kuzzle version: 2.11.2
Node.js version:  12.18.1 (running in docker https://hub.docker.com/r/kuzzleio/kuzzle-runner)
SDK version: "no sdk used"

**Comment by Aschen** [comment]
Fixed in https://github.com/kuzzleio/kuzzle/releases/tag/2.13.0
