### ISSUE TITLE
Support regex matching for Access-Control-Allow-Origin domains

### ISSUE THREAD

**Issue by Shiranuit** [kuzzleio/kuzzle#2100]
## Feature Description

Support regex in Access-Control-Allow-Origin config to verify if an origin is allowed to send requests to Kuzzle.

Browser are not consistent between them,  some send the domain name without the protocol, some send both
Firefox: `github.com`
Google Chrome: `https://github.com`

When having multiple ports or protocols it might be good to have a regular expression to avoid duplicating domains
Before
```
accessControlAllowOrigin: [
  'localhost',
  'http://localhost',
  'https://localhost',
  'console.kuzzle.io',
  'http://console.kuzzle.io',
  'https://console.kuzzle.io',
  'next-console.kuzzle.io'
  'http://next-console.kuzzle.io'
  'https://next-console.kuzzle.io'
]
```
After:
```
accessControlAllowOrigin: [
  '(http(s)?://)?localhost',
  '(http(s)?://)?console.kuzzle.io',
  '(http(s)?://)?next-console.kuzzle.io'
]
```

**Comment by Aschen** [comment]
Actually it should also be possible to have a fully custom CORS check and let developers control which requests they want to allow or not

**Comment by xbill82** [comment]
> Actually it should also be possible to have a fully custom CORS check and let developers control which requests they want to allow or not

Sounds nice. How could we enable plugins to intercept CORS-check? New pipable internal event?
