### ISSUE TITLE
Add mExists API action

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle#2133]
## Feature Description

Add the `mExists` API action to check the existence of many documents.

## Possible Solution (optional)

Use the `mGet` action

**Comment by Raksh7777** [comment]
Can I take up this issue?

**Comment by Aschen** [comment]
Yes of course @Raksh7777  ! It would be very much appreciated :-)

We planned to use the `mget` method from the ES client to check document existence and then returns 2 arrays of document IDs:
 - `successes` IDs of existing documents
 - `errors` IDs of documents not found
 
Like this API action https://docs.kuzzle.io/core/2/api/controllers/document/m-get/

**Comment by matissepage** [comment]
What can be the differences between the mGet action and the mExists action?
