### ISSUE TITLE
Write the open API specification of the controllers (documents)

### ISSUE THREAD

**Issue by clementbolin** [kuzzleio/kuzzle#2165]
## Feature Description

write the open onpe API specification for document controllers: Standard API, support for Swagger user interface

## Possible Solution (optional)
[Swagger example](https://petstore.swagger.io/l)

### Steps

**Document controller:**
- [x] count
- [x] create
- [x] get
- [x] update
- [x] replace
- [x] delete
- [x] deleteByQuery
- [x] createOrReplace
- [x] exists
- [ ] mCreate
- [ ] mCreateOrReplace
- [ ] mDelete
- [ ] mGet
- [ ] mReplace
- [ ] mUpdate
- [ ] mUpsert
- [x] scroll
- [ ] search
- [ ] updateByQuery
- [ ] upsert
- [ ] validate

**Comment by rolljee** [comment]
Followed on JIRA
