### ISSUE TITLE
Add new route server:capabilities

### ISSUE THREAD

**Issue by rolljee** [kuzzleio/kuzzle#2171]
## Description

Exposing specific properties to the configuration because `server:getConfig` / `server:info` give too much info. We want a less verbose API action.

This action should expose Kuzzle API capabilities and it will mainly used by the SDKs to customize the behavior or enable/disable some features such as:
 - splitting a `document:mCreate` action in smaller batch regarding the [limits.documentsWriteCount](https://github.com/kuzzleio/kuzzle/blob/master/.kuzzlerc.sample#L89) configuration
 - enable of disable the MemoryStorage controller if the storage engine is not Redis
 - build HTTP routes from API action name (done by the `server:publicApi` action until now)

This action could be improved over time but for the first iteration we are considering:
 - exposing Kuzzle limits
 - exposing backend for the storage and cache services (e.g. `elasticsearch` and `redis`)
 - API http routes (as in the `server:publicApi` action)
 - Kuzzle version

Route name proposal: `server:capabilities`

**Comment by Aschen** [comment]
Hello @dhillonks !
It will be very much appreciated if you could yes :-) I will update the ticket to give more informations
