### ISSUE TITLE
Replace package `openapi-enforcer`

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle#2172]
## Feature Description

This package include `js-yaml` who caused issues in the past. Also `js-yaml` has a complete JS parser as a dependency `jquery/esprima` (WTF) who takes roughly 500 Ko of memory for nothing.

![image](https://user-images.githubusercontent.com/4447392/139255742-08e819d6-5dff-4439-b341-f48004ddb45b.png)

**Comment by clementbolin** [comment]
[openapi-enforcer issue](https://github.com/byu-oit/openapi-enforcer/issues/129)
