### ISSUE TITLE
Wrong list of loaded plugin 

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle#2224]
## Description

Kuzzle print loaded plugin when it starts: `Successfully loaded 4 plugins: kuzzle-plugin-logger, kuzzle, kuzzle-plugin-auth-passport-local, workflows`

It looks like it's printing the internal application plugin as well and it shouldn't (the `kuzzle` in the example`

**Comment by clementbolin** [comment]
Hello @Aschen,
I just launched Kuzzle several times in a row, and I didn't have this problem, could you confirm that it is still there?

**Comment by Aschen** [comment]
Fixed https://github.com/kuzzleio/kuzzle/pull/2255
