### ISSUE TITLE
Truncate only delete 1000 document, not the whole collection

### ISSUE THREAD

**Issue by Erilan** [kuzzleio/kuzzle#2279]
When using the action "truncate" of the "document" controller with the javascript SDK, the collection is not cleared, only 1000 documents are removed.

## Expected Behavior
According to the documentation (https://doc.kuzzle.io/sdk/js/7/controllers/collection/truncate/) all the collection must be cleared.

## Current Behavior
Only a part of the collection is cleared (1000 documents)

## Steps to Reproduce
1. Fill a collection with 5000+ document
2. try to truncate it (kuzzle.collection.truncate(MAIN_INDEX, collectionName))

## Context (Environment)
Kuzzle version: 2.14.0
Node.js version: 14.18.2
SDK version: 7.7.1

**Comment by Aschen** [comment]
This has been fixed in Kuzzle [2.16.7](https://github.com/kuzzleio/kuzzle/releases/tag/2.16.7).

You should upgrade to the latest version
