### ISSUE TITLE
admin:resetDatabase action should also reset the mappings loading lock

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle#2297]
## Expected Behavior

The `admin:resetDatabase` action should also reset the lock that is preventing to load default mappings on each node when Kuzzle is starting.

See https://github.com/kuzzleio/kuzzle/blob/master/lib/kuzzle/kuzzle.ts#L441

**Comment by ChillPC** [comment]
Can you give a more detailed description?

**Comment by Aschen** [comment]
Actually we talked about this issue before (ping @clementbolin )

Instead of removing the lock, the lock has to be an hash of the mappings that has been charged by Kuzzle so if a new version of the mappings is available at startup, the lock became obsolete
