### ISSUE TITLE
Official OpenSearch Support

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle#2319]
## Description

Since the split between Elasticsearch and OpenSearch, we froze the version of the Elasticsearch JS SDK because further version are not compatible with OpenSearch.

Kuzzle should be shipped with both SDK and load the corresponding SDK in regard to the target storage service (ES or OpenSearch)

Also see https://github.com/kuzzleio/kuzzle/pull/2103 (but not much to see)

**Comment by HugoJalenquesPro** [comment]
Hi, is there a documentation to understand how to use Opensearch with Kuzzle ?
Thank you

**Comment by lautmat** [comment]
Same question here
