### ISSUE TITLE
Expose the human name generator

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle#2344]
## Feature Description

Expose Kuzzle human name generator in the framework https://github.com/kuzzleio/kuzzle/blob/2-dev/lib/util/name-generator.js

**Comment by bioncabond** [comment]
Hello @Aschen, 

Could you be more specific as to what you mean by _**expose**_ in the title?

**Comment by Aschen** [comment]
Hi @bioncabond 

I'm talking about exposing functions defined in this file https://github.com/kuzzleio/kuzzle/blob/2-dev/lib/util/name-generator.js

I think we could expose a static class like for the [Inflector](https://github.com/kuzzleio/kuzzle/blob/2-dev/lib/util/inflector.ts) module
