### ISSUE TITLE
Support Node.js 18 LTS

### ISSUE THREAD

**Issue by alexandrebouthinon** [kuzzleio/kuzzle#2352]
Check if we need to change something in our source code to support Node.js 18 LTS.
This should only be performed after October LTS promoting of the Node.js version 18 according to [the official planning](https://nodejs.org/en/about/releases/)

**Comment by alexandrebouthinon** [comment]
uWebSocket maintainer shipped a version that support both Node.js 14, 16 and 18 major versions (https://github.com/uNetworking/uWebSockets.js/releases/tag/v20.7.0) 
⚠️ Be sure to take this version and not the latest ones, due to performance regression occured in 14 and 16 the maintainer blacklisted this two major version for now

**Comment by psam44** [comment]
Context: Custom native Windows 11 installation, with localhost:7512 saying:
>                 "nodeVersion": "v18.13.0",
>                 "version": "2.19.12"
>                     "type": "redis", "version": "6.0.16"
>                     "type": "elasticsearch", "version": "8.6.0",
I'm using uWebSockets.js v20.19.0.tar.gz, and it provides binaries for Node.js versions 16, 18, 19.

Note: with a little workaround in kuzzle source to bypass this uWebSockets.js error:
`Error: idleTimeout must not be greater than 960 seconds!`

**Comment by Shiranuit** [comment]
NodeJS 18 Support has been release in Kuzzle 2.24.0
