### ISSUE TITLE
pipe and hook on 'generic:document:afterUpdate' wrong argument sent

### ISSUE THREAD

**Issue by screwt** [kuzzleio/kuzzle#2378]
## Expected Behavior

Hook on 'generic:document:afterUpdate' should receive the request as second argument (as stated in the doc https://doc.kuzzle.io/core/2/framework/events/generic-document/#generic-document-afterupdate)

## Current Behavior

The hook on 'generic:document:afterUpdate' receive a string as second argument (containing 'generic:document:afterUpdate')
## Steps to Reproduce

1. Initialize a project using kourou

2. Add those two plugins

```import { Plugin } from 'kuzzle';

export class FirstPlugin extends Plugin {

    async init(config, context) {
        this.config = config;
        this.context = context;
    }

    constructor () {
        super({ kuzzleVersion: '>=2.8 <3' });
        this.hooks = {
            'generic:document:afterUpdate': async (documents, request) => {
                this.context.log.info(hook generic:document:afterUpdate ${JSON.stringify(request)})
            }
        }
    }
}
```

```import { Plugin } from 'kuzzle';

export class SecondPlugin extends Plugin {

    async init(config, context) {
        this.config = config;
        this.context = context;
    }

    constructor () {
        super({ kuzzleVersion: '>=2.8 <3' });
        this.pipes = {
            'generic:document:afterUpdate': async (documents, request) => {
                this.context.log.info(`pipe generic:document:afterUpdate ${JSON.stringify(request)}`)
                return documents
            }
        }
    }
}
```

4. Create a document in any collection and then update it using the console http://console.kuzzle.io.
You will see the second argument on the hook (implemented in FirstPlugin) is a string and should be a Request

## Context (Environment)

Kuzzle version: 2.19.3
Node.js version: 14
SDK version: no SDK used

**Comment by Aschen** [comment]
Hello @screwt and thanks for your bug report!

This is addressed in this PR https://github.com/kuzzleio/kuzzle/pull/2379
