### ISSUE TITLE
Cannot use string with `range` in Koncorde query

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle#2389]
## Expected Behavior

I expect to be able to use a string with a `range` clause in a Koncorde query.

## Current Behavior

We receive an `api.assert.koncorde_dsl_error` instead.

## Steps to Reproduce

```
{
  "controller": "document",
  "action": "search",
  "body": {
    "query": {
      "range": {
        "datetime": {
          "lte": "2022-04-07 14:44:36"
        }
      }
    }
  },
  "lang": "koncorde",
  "index": "index",
  "collection": "alarms"
}
```

## Context (Environment)

Kuzzle version:
Node.js version:
SDK version:

**Comment by Shiranuit** [comment]
As stated in the documentation the `range` clause is meant to be used with `number` only

https://doc.kuzzle.io/core/2/api/koncorde-filters-syntax/clauses/#range

However if there is a need to test ranges against strings this could be discussed as a potential enhancement but this will not be the right place to, it's better to open the issue directly on the [Koncorde repository](https://github.com/kuzzleio/koncorde)
