### ISSUE TITLE
Make subscription notifications persistent

### ISSUE THREAD

**Issue by yhilem** [kuzzleio/kuzzle#2408]
### Discussed in https://github.com/kuzzleio/kuzzle/discussions/2406

<div type='discussions-op-text'>

<sup>Originally posted by **yhilem** December  4, 2022</sup>
Hi,
I want to develop an Android Mobile application that subcribe to database events with MQTT protocol : 

- "Each time a subscription is sent, a dedicated MQTT topic is created, named after the channel property issued by Kuzzle." (https://docs.kuzzle.io/core/2/api/protocols/mqtt/#app).
- Notification are meant to be dispatched on "channels" created when subscribing. (https://github.com/kuzzleio/kuzzle/blob/master/lib/core/realtime/notifier.js#L37)

What driver used by aedes for persistence (https://github.com/moscajs/aedes#persistence)?
This parameter is not specified in the Kuzzle configuration.

What happens while my app is disconnected and reconnect ? Are notifications lost ?

Thanks
Youcef HILEM
DSI BSCC La Poste</div>

**Comment by Aschen** [comment]
Hi @yhilem 

I answered you there https://github.com/kuzzleio/kuzzle/discussions/2406

**Comment by yhilem** [comment]
Thank you Adrien.
