### ISSUE TITLE
/_openapi is invalid as Swagger 2.0

### ISSUE THREAD

**Issue by psam44** [kuzzleio/kuzzle#2452]
Version 2.22.0

‌Pasted /_openapi to  editor.swagger.io‌

![image](https://user-images.githubusercontent.com/537094/234530834-453793d9-5cbd-4d9e-932b-df1e6ec7872f.png)

And so on...

**Comment by rolljee** [comment]
I've deep dive into this issue this morning.

it's seems that the format we have in no longer valid for this. I'll make a PR soon that will be focused on fixing that.
