### ISSUE TITLE
npm install error, centos7 ,please help

### ISSUE THREAD

**Issue by wolfljj** [kuzzleio/kuzzle#2474]
gcc 11 g++ 11
node v16.20.2

npm ERR! code 1
npm ERR! path /home/opc/kuzzle/node_modules/espresso-logic-minimizer
npm ERR! command failed
npm ERR! command sh -c -- node-gyp rebuild
npm ERR! make: “/home/opc/kuzzle/node_modules/espresso-logic-minimizer/build”
npm ERR!   g++ -o Release/obj.target/EspressoLogicMinimizer/bridge/addon.o ../bridge/addon.cc '-DNODE_GYP_MODULE_NAME=EspressoLogicMinimizer' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/home/opc/.cache/node-gyp/16.20.2/include/node -I/home/opc/.cache/node-gyp/16.20.2/src -I/home/opc/.cache/node-gyp/16.20.2/deps/openssl/config -I/home/opc/.cache/node-gyp/16.20.2/deps/openssl/openssl/include -I/home/opc/.cache/node-gyp/16.20.2/deps/uv/include -I/home/opc/.cache/node-gyp/16.20.2/deps/zlib -I/home/opc/.cache/node-gyp/16.20.2/deps/v8/include -I../../nan -I../espresso-src  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -std=c99 -Wno-misleading-indentation -Wno-unused-result -Wno-format-overflow -Wno-implicit-fallthrough -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++14 -MMD -MF ./Release/.deps/Release/obj.target/EspressoLogicMinimizer/bridge/addon.o.d.raw   -c
npm ERR!   cc -o Release/obj.target/EspressoLogicMinimizer/bridge/bridge.o ../bridge/bridge.c '-DNODE_GYP_MODULE_NAME=EspressoLogicMinimizer' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/home/opc/.cache/node-gyp/16.20.2/include/node -I/home/opc/.cache/node-gyp/16.20.2/src -I/home/opc/.cache/node-gyp/16.20.2/deps/openssl/config -I/home/opc/.cache/node-gyp/16.20.2/deps/openssl/openssl/include -I/home/opc/.cache/node-gyp/16.20.2/deps/uv/include -I/home/opc/.cache/node-gyp/16.20.2/deps/zlib -I/home/opc/.cache/node-gyp/16.20.2/deps/v8/include -I../../nan -I../espresso-src  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -std=c99 -Wno-misleading-indentation -Wno-unused-result -Wno-format-overflow -Wno-implicit-fallthrough -O3 -fno-omit-frame-pointer  -MMD -MF ./Release/.deps/Release/obj.target/EspressoLogicMinimizer/bridge/bridge.o.d.raw   -c
npm ERR! make: “/home/opc/kuzzle/node_modules/espresso-logic-minimizer/build”
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/home/opc/.nvm/versions/node/v16.20.2/bin/node',
npm ERR! gyp verb cli   '/home/opc/kuzzle/node_modules/.bin/node-gyp',
npm ERR! gyp verb cli   'rebuild'
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@16.20.2 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb find Python Python is not set from command line or npm configuration
npm ERR! gyp verb find Python Python is not set from environment variable PYTHON
npm ERR! gyp verb find Python checking if "python3" can be used
npm ERR! gyp verb find Python - executing "python3" to get executable path
npm ERR! gyp verb find Python - executable path is "/usr/bin/python3"
npm ERR! gyp verb find Python - executing "/usr/bin/python3" to get version
npm ERR! gyp verb find Python - version is "3.6.8"
npm ERR! gyp info find Python using Python version 3.6.8 found at "/usr/bin/python3"
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 16.20.2
npm ERR! gyp verb command install [ '16.20.2' ]
npm ERR! gyp verb install input version string "16.20.2"
npm ERR! gyp verb install installing version: 16.20.2
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 11
npm ERR! gyp verb needs "installVersion" 11
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 16.20.2
npm ERR! gyp verb build dir attempting to create "build" dir: /home/opc/kuzzle/node_modules/espresso-logic-minimizer/build
npm ERR! gyp verb build dir "build" dir needed to be created? Yes
npm ERR! gyp verb python symlink creating symlink to "/usr/bin/python3" at "/home/opc/kuzzle/node_modules/espresso-logic-minimizer/build/node_gyp_bins/python3"
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: /home/opc/kuzzle/node_modules/espresso-logic-minimizer/build/config.gypi
npm ERR! gyp verb config.gypi checking for gypi file: /home/opc/kuzzle/node_modules/espresso-logic-minimizer/config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: /home/opc/kuzzle/node_modules/espresso-logic-minimizer/common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/opc/kuzzle/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/opc/kuzzle/node_modules/espresso-logic-minimizer/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/opc/kuzzle/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/opc/.cache/node-gyp/16.20.2/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/opc/.cache/node-gyp/16.20.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/opc/kuzzle/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/opc/.cache/node-gyp/16.20.2/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/opc/kuzzle/node_modules/espresso-logic-minimizer',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp verb command build []
npm ERR! gyp verb build type Release
npm ERR! gyp verb architecture x64
npm ERR! gyp verb node dev dir /home/opc/.cache/node-gyp/16.20.2
npm ERR! gyp verb `which` succeeded for `make` /usr/bin/make
npm ERR! gyp verb bin symlinks adding symlinks (such as Python), at "/home/opc/kuzzle/node_modules/espresso-logic-minimizer/build/node_gyp_bins", to PATH
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! cc1plus: warning: command-line option ‘-std=c99’ is valid for C/ObjC but not for C++
npm ERR! In file included from ../bridge/addon.cc:2:
npm ERR! /home/opc/.cache/node-gyp/16.20.2/include/node/node.h:887:7: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
npm ERR!   887 |       (node::addon_register_func) (regfunc),                          \
npm ERR!       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! /home/opc/.cache/node-gyp/16.20.2/include/node/node.h:921:3: note: in expansion of macro ‘NODE_MODULE_X’
npm ERR!   921 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
npm ERR!       |   ^~~~~~~~~~~~~
npm ERR! ../bridge/addon.cc:91:1: note: in expansion of macro ‘NODE_MODULE’
npm ERR!    91 | NODE_MODULE(EspressoLogicMinimizer, init)
npm ERR!       | ^~~~~~~~~~~
npm ERR! make: execvp: cc: not folder
npm ERR! make: *** [Release/obj.target/EspressoLogicMinimizer/bridge/bridge.o] error 127
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/opc/kuzzle/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Linux 3.10.0-1160.95.1.el7.x86_64
npm ERR! gyp ERR! command "/home/opc/.nvm/versions/node/v16.20.2/bin/node" "/home/opc/kuzzle/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/opc/kuzzle/node_modules/espresso-logic-minimizer
npm ERR! gyp ERR! node -v v16.20.2
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok

**Comment by rolljee** [comment]
I'll close this issue, feel free to reopen if needed
