### ISSUE TITLE
Documentation is not clear on what join method of realtime does.

### ISSUE THREAD

**Issue by ScreamZ** [kuzzleio/kuzzle#2517]
Hi,

I'm writing my own new TypeScript SDK because I'm not happy with the provided one and this helps me understand how Kuzzle works under the hood. Therefore I want to implement the auto-resubscribe feature.

I could only make new same calls to `subscribe` method but I want to understand what's the purpose of `join` method.

What is the behavior of https://docs.kuzzle.io/core/2/api/controllers/realtime/join/ ? As it doesn't take a `channelID` does it re-subscribe to all possible channelID ? as a channelID is `roomID-channelHASH`? Or this method is totally random and deprecated?

As far as I can see it only calls createRoom for `hotelClerk`  but then I don't get it.

https://github.com/kuzzleio/kuzzle/blob/96ac03b60c19aa60128117f8a59eba9ec1969c5b/lib/core/realtime/hotelClerk.ts#L117-L122
https://github.com/kuzzleio/kuzzle/blob/96ac03b60c19aa60128117f8a59eba9ec1969c5b/lib/core/realtime/hotelClerk.ts#L314-L334

**Comment by rolljee** [comment]
>I'm writing my own new TypeScript SDK because I'm not happy with the provided one and this helps me understand how Kuzzle works under the hood. Therefore I want to implement the auto-resubscribe feature.


What is wrong with the provided one ?


What the join function do is 

It checks if the room with the given roomId exists in the current node's rooms. If it does, no further action is taken and the function ends.

If the room doesn't exist on the current node, it tries to fetch the normalized filters for the room from the cluster. This is done using the global.kuzzle.ask function with the command "cluster:realtime:filters:get" and the roomId as arguments.

If no normalized filters are returned (i.e., the room doesn't exist on any node in the cluster), it throws a room_not_found error.

If the normalized filters are returned, it creates the room on the current node using the createRoom method and the normalized filters as an argument.

If the room doesn't exist on the current node, it tries to fetch the normalized filters for the room from the cluster. 

If no normalized filters are returned (i.e., the room doesn't exist on any node in the cluster), it throws a room_not_found error.

If the normalized filters are returned, it creates the room on the current node

**Comment by ScreamZ** [comment]
Thanks @rolljee for your answer.

## About your answer

So if I'm correct there is no real usage of it from the end user point of view? I can totally rely on `subscribe` to achieve the same effect and effectively subscribe.

Is there any way to get the filter from the roomID in a request/response? Or should i implement my own layer over it ?

## More generally

The SDK is not adapted to ReactJS usage with `useEffect` running twice in a row for optimization and also lifecycle. I know this has been developed with VueJS in mind, as it's the favorite framework of the team originally.

**Don't take it personally for my next words**,

but I'm trying to get support on things, but no one answered on Discord, or GitHub even when we make pull requests to improve the product or ask for support on potential bugs, we are still alone.

**I know you have priorities**, especially on the IoT platform. **I don't have paid support**, and **I understand that I can't ask for a quick answer of hours/days, but it's been weeks**. But people working for free making pull requests helping improve the product, isn't a good reason to not let them alone? **Is the political decision to abandon OSS?**

I'm very disappointed because I'm a former Kaliop and used to play with the Kuzzle team and I know that before the OSS area was more reactive and open to suggestions. The product has great potential but today it looks like it's a dead product from the open-source point of view, which is sad. This also let the concurrency rise where you were precursor, supabase, appwrite, and many others. You still have some unique features, but is it worth the risk?

All of this led me to write my own SDK with a focus on Websocket, typescript integration, stable auto-reconnect, and re-subscribe, and a proper gestion of subscriptions of documents/presence. Took me weeks, but it's stable. For now I'm happy with it, but as issues rises, I'm not sure how to build my new white brand tool on Kuzzle on the long run.

Even though the documentation is opaque at some point it leads me to ask some questions to you, Kuzzle V2 also contains a lot of legacy code with strange behavior. Like the `room` property of the payload that is sometimes `requestID` for request or the real room ID for notifications.

Wish you a nice day,
Regards
