### ISSUE TITLE
./bin/kuzzle install fails

### ISSUE THREAD

**Issue by jveres** [kuzzleio/kuzzle#264]
(git clone main)
npm install
./bin/kuzzle install
error:
```
███ kuzzle-plugins: Updating plugins configuration...
/root/kuzzle/node_modules/proper-lockfile/index.js:178
    compromised = compromised || function (err) { throw err; };
                                                  ^

Error: Unable to update lock within the stale threshold
    at createError (/root/kuzzle/node_modules/err-code/index.js:4:44)
    at /root/kuzzle/node_modules/proper-lockfile/index.js:107:21
    at FSReqWrap.oncomplete (fs.js:117:15)
```

**Comment by jveres** [comment]
If you issue ```./bin/kuzzle install``` again it seems to work.

**Comment by scottinet** [comment]
Hi,

I already had this bug and solved it. So our [latest Kuzzle release](https://github.com/kuzzleio/kuzzle/releases/tag/1.0.0-RC2) should not be impacted, and I wasn't able to reproduce this a few minutes ago (starting from a fresh repo clone from the master branch).

If you still have it with a fresh git clone, can you please provide us with:
- the complete list of executed commands (for instance, it's not possible to execute a `kuzzle install` command without a live Elasticsearch anymore)
- the complete output log

**Comment by scottinet** [comment]
edit: I took a look at the code, and it *might* still be possible to get this error, under certain conditions.

I just need you to confirm you still have it with our latest release :-)

**Comment by jveres** [comment]
Hi,
I git cloned the latest sources from the main branch. It has 1.0.0-RC2 version in package.json.

**Comment by scottinet** [comment]
Ok. I think I see from where that error comes from.

I'm preparing a hotfix for it, stay tuned.

**Comment by scottinet** [comment]
@jveres > a hotfix is available. You can test it by cloning [this branch](https://github.com/kuzzleio/kuzzle/tree/hotfix-264-kuzzle-install-fails) while the team reviews it.
