### ISSUE TITLE
iOS SDK availability

### ISSUE THREAD

**Issue by Rajan** [kuzzleio/kuzzle#287]
kuzzle is nice. Question: When can one expect the iOS support?

**Comment by j33f** [comment]
Right now https://github.com/kuzzleio/sdk-ios 😊

**Comment by scottinet** [comment]
Hi !
The SDK documentation has also been updated for Swift and Objective C on our development branches, and it should be released this week on our website. :-)

**Comment by scottinet** [comment]
Our monthly release has been postponed a bit, until we finish some major improvements to Kuzzle code.

**Comment by hery84** [comment]
Some news? 

regards.

**Comment by scottinet** [comment]
Hi,

Kuzzle's native iOS SDK has been discontinued for now, as it requires a lot of work to maintain (especially with Swift breaking changes), and we don't have much demand for it at the moment.

About Kuzzle SDKs: we're currently working on a [C SDK](https://github.com/kuzzleio/sdk-go/tree/master/internal/wrappers) (derivated from our Go SDK). The main goal behind that project is to allow us to release SDKs in many languages using [SWIG](http://www.swig.org).

So, the good news is: in the near future, you'll have a C SDK that you'll be able to import & use in Objective-C projects.

The bad news: we have currently no plan on working on a Swift SDK again, especially considering that projects we're working on involving iOS are made with [React Native](https://facebook.github.io/react-native/)

**Comment by scottinet** [comment]
Hi @hery84, 

Kuzzle's native iOS SDK has been discontinued for now, as it requires a lot of work to maintain (especially with Swift breaking changes), and we don't have much demand for it at the moment.

About Kuzzle SDKs: we're currently working on a [C SDK](https://github.com/kuzzleio/sdk-go/tree/master/internal/wrappers) (derivated from our Go SDK). The main goal behind that project is to allow us to release SDKs in many languages using [SWIG](http://www.swig.org).

So, the good news is: in the near future, you'll have a C SDK that you'll be able to import & use in Objective-C projects.

The bad news: we have currently no plan on working on a Swift SDK again, especially considering that projects we're working on involving iOS are made with [React Native](https://facebook.github.io/react-native/)
