### ISSUE TITLE
Docker execution on MacOS X & Windows throws a npm "EPROTO" error

### ISSUE THREAD

**Issue by scottinet** [kuzzleio/kuzzle#29]
When trying to launch the Kuzzle docker image on MacOS X or Windows, you may receive a "EPROTO" error coming from npm.
This is due to a VirtualBox bug introduced in the 5.0.4 version, and solved in the 5.0.5 version.

This bug is tracked here: https://www.virtualbox.org/ticket/14563

If you encounter this problem, you can solve it either by upgrading your VirtualBox version to 5.0.5 if available on your platform, or by downgrading it to the 5.0.2 version otherwise.

If it isn't possible for you to change your VirtualBox version, you may also try the following workaround:

* Copy the docker-compose file at the root of Kuzzle directory and add the following line:
```sh
command: tail -f /dev/null
```

* Launch docker-compose on this file
* On another terminal, execute the following command line:
```sh
docker exec -ti kuzzle_kuzzle_1 bash
```

* Once there, execute this command to install the necessary dependencies:
```sh
npm install --no-bin-links
``` 

You should then be able to launch Kuzzle normally using the provided docker-compose files.

**Comment by AnthonySendra** [comment]
@scottinet Because the `npm install` is done on build, can we delete this issue ?

**Comment by scottinet** [comment]
You're right, this is not an issue anymore.
