### ISSUE TITLE
Offline mode example

### ISSUE THREAD

**Issue by ecerroni** [kuzzleio/kuzzle#301]
Question:

Is there any detailed example or tutorial of the SDK offline mode (javascript) implementation? 

Thanks.

**Comment by scottinet** [comment]
Hi,

Not yet, all we have for now is [a lengthy explanation](http://kuzzle.io/sdk-documentation/#offline-mode).

Is there anything we can do to assist you?

**Comment by ecerroni** [comment]
Thanks. In the next weeks, when I find some free time, I'll try to build a sample app following the docs.

I'll ask for further assistance as I need. What would be the best channel for that to contact you?

**Comment by scottinet** [comment]
That would be very nice!
You can come talk to us directly on [gitter](https://gitter.im/kuzzleio/kuzzle), that way you should get answers quickly.
