### ISSUE TITLE
Can I use RethinkDB with Kuzzle ?

### ISSUE THREAD

**Issue by meepeek** [kuzzleio/kuzzle#373]
I don't know much about elasticsearch and how to setup and RethinkDB is easy to setup and scale so I wonder if I could switch to Rethink in the future if a system were go on production

**Comment by meepeek** [comment]
Any update ?

**Comment by ballinette** [comment]
Hi, and thank you for your interest about Kuzzle ;)

To be short, we can answer the same as for MongoDB (see issue #364 )

Actually, Kuzzle data layer is strongly dependent to Elasticsearch, and the question to enable its replacement by another service is still under debate within the team.

Technically, we use the same filtering syntax as Elasticsearch in our API, so just "switch to Rethink" (or any other database service) is not as simple as this. For that we'll need to:
* implement a StorageEngine for Rethink with all methods of current engine
* and add methods to translate requests with elastic-like syntax filters to rethink syntax

Another option would be to not switch between Elastic and Rethink, but just add a support to Rethink, using a specific plugin (see http://kuzzle.io/guide/#gt-controllers), as we already made for Redis, with the [Memory Storage Controller](http://kuzzle.io/api-reference/#description)

**Comment by ballinette** [comment]
Anyway, if you just worry about how to setup and scale Elasticsearch, it's not so difficult, and we will write soon some documentation about this (in addition to elastic's official one) ;)

**Comment by ballinette** [comment]
I'm closing this issue. 
You can refer to discussion in #364 , which is about quite the same needs ;)
