### ISSUE TITLE
Why not using Redis instead of ES for internal engine?

### ISSUE THREAD

**Issue by AnthonySendra** [kuzzleio/kuzzle#384]
Hello Kuzzle Team :),

I'm wondering if the internal index `%kuzzle` has its place in ES. I mean, Plugins, Services, etc are only used by Kuzzle for internal usages. We don't need to perform complex searches on this index. The only use case (tell me if I'm wrong) is to get the configuration by key and that's it.
Maybe it's about replication? But I guess we can also use the Redis replication for let all Kuzzle know about new services, or plugins configurations.

I have the feeling that we're decoupling (yes, a very tiny little bit) Kuzzle from ES if `internalEngine` is working with Redis. And if we think about it, it's weird to store internal configuration inside a search engine.

I'm not at this office for putting a post-it on the window, so I let an issue instead :). We could talk about it when I'm back.

See you soon team.

**Comment by ballinette** [comment]
The `internalEngine` is also used for the repositories, and for this we need to have advanced search features (for example, to fetch a user by its github ID)

But I agree that we should discuss about trying to decouple a bit Kuzzle from ES ;)

**Comment by scottinet** [comment]
Interesting idea. I need to play with it a bit: if I agree/don't really care about where configuration data is stored (plugins, server configuration, and so on), I wonder if storing our right management system in Redis is feasible.
I took a quick glance to the Redis API documentation, and unless I'm mistaken, just getting a list of users using a particular profile seems to be a tedious task using Redis.

Moreover, we may still need an internal index in ElasticSearch to store meta information about collections, for instance to emulate the old `DeleteCollection` route, using some kind of trashcan system.

**Comment by AnthonySendra** [comment]
I didn't talk about roles, profiles and users. My first idea is just to store internal things inside redis. Not users, roles, etc. Just things that kuzzle needs to run. Services configurations and plugins. For me, user management is not a part of internalEngine. It's data like other documents. 

We have to let user the capability to perform a search like on the username or something and it's not feasible :( (with complex text search).
It's about separate "business data"  (that includes users) from "internal data". Conceptually, for me, it's weird to store internal functional data inside a search engine. 

But maybe it's add complexity to add internal data inside redis.

**Comment by j33f** [comment]
What about the problems with redis replication ? @ballinette has spot something intéresting on Redis: in clusters, you could have only one index...
What about PouchDB or SQLite ?

**Comment by AnthonySendra** [comment]
@jeff: it's not a real problem. You can prefix keys. This is what we have to do for already existing indexes in kuzzle.

But with sentinel a think we can still use multi index.
I really don't think adding new depencies like PouchDB or something is a good idea.

**Comment by j33f** [comment]
it depends on the goal: if the goal is to be agnostic from the data storage, using something like pouch or sqlite could be an option... so the question is: why storing all we are storing into %kuzzle currently in ES elsewhere ?

**Comment by scottinet** [comment]
Outdated concerns
