### ISSUE TITLE
kuzzle start without kuzzle install

### ISSUE THREAD

**Issue by AnthonySendra** [kuzzleio/kuzzle#403]
The first time we ran kuzzle with `kuzzle start` (or with PM2), Kuzzle crashed because the index `%kuzzle` is not already created. The `kuzzle install` command has to be run before the `start`.

We probably have to make an implicit `install` on first `start` if the index does not exist, in order to execute `pm2 start /process.json` without to do `kuzzle install` before.

**Comment by benoitvidis** [comment]
Additionally, the bootstrap process should check:

1. the availability of the plugin source (i.e. npm package)
2. the configuration init in db

If so, the kuzzle install cli command becomes useless and can be removed
