### ISSUE TITLE
Kuzzle crashes if unable to load a plugin

### ISSUE THREAD

**Issue by scottinet** [kuzzleio/kuzzle#412]
If a plugin cannot be loaded because of some sort of error (for instance, a syntax error), then Kuzzle crashes.

Instead, it should catch the problem and simply remove the plugin at fault from its active plugins.

**Comment by ScreamZ** [comment]
Is this fix handling moved plugins that are reference from path ?
Getting an issue like that when I tried to rename my plugin folder and the kernel wasn't able to find the module at the old location.

Unable to call any cli command nor load the kernel.

Thanks for the answer
