### ISSUE TITLE
Is there a feature for develop desktop app with offline database ?

### ISSUE THREAD

**Issue by meepeek** [kuzzleio/kuzzle#425]
Please let me know if there were any related practices or future plans

**Comment by xbill82** [comment]
Hey @meepeek just to be sure to understand.
What do you mean exactly by "desktop app with offline database"? Sounds like you want to embed Kuzzle in a standalone app executable. Am I on the right track?

**Comment by meepeek** [comment]
Yep. Something like that. I am a Meteor fan so offline DB sync is addicted.

**Comment by xbill82** [comment]
Ok. So far, we never intended Kuzzle to be/become an application framework, but rather as a on-premise backend, so I guess it will stay this way for a long time. We are planning many evolutions for the mid-far future, but not the ability to embed it in a desktop application.
By the way, I would consider embedding Kuzzle to have offline DB sync quite an overkill solution. Kuzzle is there to enable you to store your user's data, which doesn't impeach you from caching it client-side for offline workflows.

My approach to your problem would be to develop some kind of middleware for the Kuzzle SDK enabling all the data to be cached on some sort of NoSQL client-side database which would be embedded in the application. This way, the SDK would transpaently route the requests to the backend or the local DB depending on the state of the connection.

This is all I know for the moment. Hope it helps.
