### ISSUE TITLE
Let Kuzzle store its internal data in a seperate db

### ISSUE THREAD

**Issue by jenow** [kuzzleio/kuzzle#439]
- Generalize InternalEngine use for Security & config components
- Allow the InternalEngine to point to a separate database
- Isolate Redis internal use cases and allow injecting a new Redis configuration/server

**Comment by ballinette** [comment]
Issue moved to [kuzzleio/kuzzle-backlog #118](https://github.com/kuzzleio/kuzzle-backlog/issues/118) via [**ZenHub**](https://www.zenhub.com/)
