### ISSUE TITLE
Implement ES reindex method 

### ISSUE THREAD

**Issue by jenow** [kuzzleio/kuzzle#442]
Reference: 
- https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html
- https://www.elastic.co/blog/changing-mapping-with-zero-downtime

**Comment by ballinette** [comment]
Issue moved to [kuzzleio/kuzzle-backlog #116](https://github.com/kuzzleio/kuzzle-backlog/issues/116) via [**ZenHub**](https://www.zenhub.com/)
