### ISSUE TITLE
Expose renameCollection API route

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle#463]
First we need to explore the possibility to do this using ElasticSearch API. 
If this is not possible, we need to emulate this functionality using the write.move API route and then "delete" the collection using collections metadata

May depend on #462

**Comment by gandbox** [comment]
Good exemple about : why we need a CLI : kuzzle migrate-collection collection1 collection2 (will create new collection, copy schema, coy data & remove previous collection)
