### ISSUE TITLE
New DSL

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle#481]
Our first benchmark tests show that our current DSL implementation lacks performance. It has a hard time handling thousands of users and the more there are, the slower the DSL is.
This issue is to keep track of the new DSL implementation, following this architecture workshop document: https://confluence.kaliop.net/display/LABS/2016-09-12+New+DSL+architecture+v2

**Comment by scottinet** [comment]
Fix: #510

**Comment by xbill82** [comment]
:tada:
