### ISSUE TITLE
Do we still need the Vagrant install?

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle#578]
After a short talk with @ballinette we started doubting about the utility of the Vagrant installation process. The Vagrant files are currently lost into oblivion and don't seem to be kept up to date.

Proposals are

* Wipe out the Vagrant files, or
* Update them and move them to a separate repository

**Comment by ballinette** [comment]
Agree with the idea to wipe out the vagrant files:
As far as I know nobody is actually using kuzzle through vagrant (except me for development, but with a custom non generic vagrant instance).

And for people who want to test kuzzle, 2 main options are given:
* either use Docker and our docker-compose files
* or install Kuzzle manually (that they can do over Vagrant if they want to).

Let's remove the vagrant settings within this repo, and the "Vagrant install" chapter in the doc to clarify things, it with save use time to maintain this.

And if in the future some people ask us for a specific vagrant installation, it will still be possible to create a dedicated repository with vagrant config.

**Comment by benoitvidis** [comment]
:+1: on removing it. 
Would maybe make sense if we built a custom vagrant box but the current setup to transport docker has become useless.

**Comment by scottinet** [comment]
I agree: we should first concentrate on a few supported OSes to support.
