### ISSUE TITLE
Always install plugin on startup

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle#602]
I'm working on a plugin development stack at https://github.com/kuzzleio/kuzzle-plugin-template/tree/dev-scaffolding
My goal is to create a stack that enables someone to start developing a Kuzzle plugin from scratch within one command. The docker-compose stack mounts the plugin code as a volume on `/tmp` and PM2 watches this directory to restart the Kuzzle Core on every modification. The goal is that Kuzzle Core reinstalls the plugin with the latest version of the code on every startup.

Unfortunately, this doesn't seem possible since the PluginPackage manager keeps track of the version of the plugin and compares it with the instance that is installed on `node_modules`, so that the plugin is installed only at the first startup.
We need to find a suitable solution to enable the "watch" feature on plugin development.

**Comment by benoitvidis** [comment]
@xbill82 Following our recent discussion, I believe this subject is tacked in #609.
Can we close this issue?

**Comment by xbill82** [comment]
Yep!
