### ISSUE TITLE
Plugin management refactor

### ISSUE THREAD

**Issue by benoitvidis** [kuzzleio/kuzzle#609]
Question: While this issue addresses several points at once, I believe they most of them are dependent on each-other and cannot be easily be split into several different issues. This is of course open to discussion.

# Situation

For the time being, plugins are installed during Kuzzle startup, which downloads the packages and their dependencies and writes their configuration in the database.
This leads to several issues, including:

* First startup is delayed, possibly generating some useless timeout errors
* Kuzzle needs an active internet connection on start
* Plugins are not easy to migrate from an instance to another, mostly because of the database settings
* Plugins versions are difficult to handle during a migration process.

The aim of this proposal is to simplify the installation of plugins.

# Proposal

Main principles:

* rely on the file system only to know which plugins should be loaded/activated
* configuration is in one place only (kuzzle one)

## Installation

Installing a plugin should be as simple as dropping a folder in a dedicated location.
Similar to Apache, here is the proposed plugin directory organization:

```
kuzzle
└── plugins
    ├── available
    │   ├── plugin1
    │   └── plugin2
    └── enabled
        └── plugin1 -> ../available/plugin1
```

* Each plugin is a folder inside `plugins/enabled`. 
* In order to easily activate or deactivate, the default setup proposes to symlink the plugin folder from the `available` directory
* During startup, Kuzzle lists the plugins in the `enabled` folder and requires them.

## Default plugins

Default plugins can directly be bundled in Kuzzle installation.
Extra core team plugins (i.e. oauth authentication strategy) can be bundled too and left unactivated.

## Plugin development

* Plugins do not need to be a module anymore. They just need to be requireable.
* From the above point, we should not enforce plugins to ship a default configuration in the package.json anymore, which was quite dirty IMO anyway.
Plugins should be responsible to set their default configuration and use the overriden one given during init from Kuzzle.

**Comment by xbill82** [comment]
Ok, I think we covered this when we talked about it but... What about plugins that have external dependencies? Like, ok, they don't need to be a proper NodeJS module, but what if they actually _need_ to be a module, in order to ship with a set of dependencies specified in a `package.json` file?
The real questions are

* where are these dependencies installed? Root Kuzzle `node_modules` dir or per-plugin `node_modules`? (It's actually more a question about how npm behaves)
* The CLI should be in charge of calling the `npm install` after enabling the plugin, I guess, only if a `package.json` file is found, right?

**Comment by ballinette** [comment]
* If I remember, we pointed that each plugin should have its own `node_modules`, to avoid possible version conflicts btw. dependencies of different plugins.
* About `npm install` into each plugin, ihmo, it has to be done at plugin installation/packaging step (just after copying the plugin in `plugins/available/`), not  while enabling it.

**Comment by xbill82** [comment]
Here's a little TODO list for the implementation.

- [ ] get rid of `pluginPackage.js`
- [ ] get rid of `PluginPackagesManager::bootstrap`
- [ ] adapt `PluginPackagesManager::definitions` to scan the directory tree and get the plugin definition, either from the directory name or the `package.json`
- [ ] adapt `PluginsManager::run` to pass the custom config to the `init` function
- [ ] get rid of the CLI commands
