### ISSUE TITLE
Delete by query Users/Roles/Profiles

### ISSUE THREAD

**Issue by AnthonySendra** [kuzzleio/kuzzle#619]
Hello,

Because we can't perform a `.deleteDocument` on the index `%kuzzle` we can't delete users/roles/profiles with a query (or simply with an array of IDs).

We need to have a way to delete mutli user/profile/role in Kuzzle and in SDKs.

**Comment by benoitvidis** [comment]
Real need is more a mDelete, which should be handled by https://github.com/kuzzleio/kuzzle/pull/616 or from there IMO.

I propose we close this issue till we don't have any need yet and these methods would be potentially dangerous to use.

**Comment by benoitvidis** [comment]
@AnthonySendra can we consider this issue as done?
