### ISSUE TITLE
Error: EACCES listen broker.sock

### ISSUE THREAD

**Issue by benoitvidis** [kuzzleio/kuzzle#621]
If kuzzle configuration includes a relative socket path and that pm2 cwd is not configured to the home of kuzzle, we get this error is pm2 cwd does not contain a writeable run folder.

We need to make sure relative path are handled from kuzzle root dir.

**Comment by Cooker-Monster** [comment]
Kuzzle on Mac Os (El capitan) shows the same "Error: connect EACCES ./run/broker.sock" I can't figure out what going wrong (Kuzzle user newbie status !). 
Context: Linux installation kind without Docker (Redis & Elasticsearch pre installed).
Thx !

**Comment by benoitvidis** [comment]
@Cooker-Monster : Do you use pm2 to manage Kuzzle?
If so, do you have a cwd attribute in your configuration file, and if you have, does it point to your kuzzle root directory?

**Comment by Cooker-Monster** [comment]
I used pm2 and cwd was blank ... I gave up, I have switched to Docker realm ... don't have this message anymore and Kuzzle seems running well.
I must dig in API, another topic by now ...
