### ISSUE TITLE
Error DeleteDocument with refresh

### ISSUE THREAD

**Issue by AnthonySendra** [kuzzleio/kuzzle#625]
```
kuzzle
  .dataCollectionFactory('collection', 'index')
  .deleteDocumentPromise({query: {ids: {values: ids}}}, {refresh: 'wait_for'})
```

The error is `legal_argument_exception] request [/mycollection/otherCollection/_search] contains unrecognized parameter: [refresh]`
This is because we do a search before the delete and we put option with `refresh` and this is not supported by search method.

**Comment by xbill82** [comment]
Directly related to #682

**Comment by xbill82** [comment]
After taking a look to the code, I'm not sure the `refresh` option is passed to the ES client. Am I missing something?

**Comment by xbill82** [comment]
Ok, as per https://github.com/kuzzleio/kuzzle/blob/master/lib/services/elasticsearch.js#L531 I confirm we do not pass the extra params to the `bulk` ES action. Should we fix this?

**Comment by xbill82** [comment]
By the way, #686 solves this issue (i.e. passing `refresh` to `deleteByQuery` does not fail anymore).
