### ISSUE TITLE
Kuzzle returns nothing when body is not what Kuzzle wants

### ISSUE THREAD

**Issue by AnthonySendra** [kuzzleio/kuzzle#631]
Hello,

When I execute something like this with JS SDK:
```
return kuzzle
    .queryPromise({controller: 'security', action: 'mDeleteUsers'}, {body: ['toto']})
```

My promise is never resolve nor reject, Kuzzle returns nothing. This is because Kuzzle wants `{body: {ids: ['toto']}}`. But I guess Kuzzle must returns an error with "malformed body, missing 'ids' attribute" or something.
This is not only for `security/mDeleteUsers`, also tested with `document/mDelete` (and probably for many others routes)

**Comment by scottinet** [comment]
Reproduced. Nothing is logged Kuzzle-side, will try to figure what's going on.

**Comment by scottinet** [comment]
Got it.

The problem does not come from Kuzzle but from the Websocket plugin.

I'm closing this issue in favor of this one: https://github.com/kuzzleio/kuzzle-plugin-websocket/issues/15
