### ISSUE TITLE
Should enforce JSON content only for native API routes

### ISSUE THREAD

**Issue by scottinet** [kuzzleio/kuzzle#634]
Currently, Kuzzle forces incoming requests to be in JSON format for all possible API routes.

Instead, it should restrict this check only for the native API routes. We shouldn't force plugins to accept JSON, as there are cases where supporting other formats would be beneficial.

Use case: CSV data import route

**Comment by gandbox** [comment]
@kuzzleio/owners still needed after WRBM & CMX projects ?

**Comment by stafyniaksacha** [comment]
Yes, we need to allow plugins to handle what they want in input

**Comment by ballinette** [comment]
I guess this is more a proxy-related issue.

Note that for the CSV data import use case, it's not needed anymore as the proxy is now able to manage file upload through HTTP, the file data is then given to Kuzzle as a base64-encoded JSON attribute (see https://github.com/kuzzleio/kuzzle-proxy/pull/47 )

**Comment by ballinette** [comment]
I guess the way the HTTP entrypoint manage incoming request now is OK for all use cases.
Feel free to reopen the issue if there is a use case that is not correctly managed.
