### ISSUE TITLE
Problem with elesticsearch at first install

### ISSUE THREAD

**Issue by melkir** [kuzzleio/kuzzle#641]
After running

> $ wget https://raw.githubusercontent.com/kuzzleio/kuzzle-build/master/docker-compose/kuzzle-docker-compose.yml
> $ docker-compose -f kuzzle-docker-compose.yml up

I got many messages that tells me that elasticsearch isn't working

> kuzzle_1         | [2017-01-27 15:03:26+00:00] - Still trying to connect to http://elasticsearch:9200

Any idea ?

**Comment by henninghorn** [comment]
I'm getting the same error.

**Comment by ballinette** [comment]
Hi
You have to increase the "mmap counts" to permit Elasticsearch container to run properly. (see here for more explanations: https://www.elastic.co/guide/en/elasticsearch/reference/5.x/vm-max-map-count.html )

Run following command just before `docker-compose up` :
```
sudo sysctl -w vm.max_map_count=262144
```

**Comment by scottinet** [comment]
Our documentation has been updated a few days ago to reflect this constraint: http://docs.kuzzle.io/guide/#docker

Kuzzle's main README file has also been updated on the `develop` branch: https://github.com/kuzzleio/kuzzle/pull/652

I'm closing this issue.
