### ISSUE TITLE
Security on data collection subscription

### ISSUE THREAD

**Issue by PierreCavalet** [kuzzleio/kuzzle#668]
I'm using a plugin controller as a middleware between my client and an API REST. I use the API token to authenticate my users. Only the user knows his token.

In a particular case, I have to retrieve data through SSE feed which I then forward to the client using Kuzzle data collection. I use my plugin to send data to Kuzzle and I subscribe with each client.

I'm then filtering on the token so each client knows which data it has to take. The problem is that the token is a sensitive data, so if a client subscribe without filtering, he is going to see every token. 

I could eventually subscribe to different collection using the token in the collection name, for example:

```
kuzzle
  .dataCollectionFactory('collection_my_token', 'index')
  .subscribe({}, function (error, result) {
    // do something
  })
  .onDone(function (err, kuzzleRoomInstance) {
    // Handles the subscription result. 
  });
```

Is there any better solution to send data only to a specific user without "tweaking" the process ?

**Comment by scottinet** [comment]
Outdated, but for the record: it's the plugin's responsability to expose only non-sensitive data.
