### ISSUE TITLE
Add a createOrUpdate route for documents

### ISSUE THREAD

**Issue by scottinet** [kuzzleio/kuzzle#676]
Currently Kuzzle handles the following creation options:

* create: if the _id already exists, the request ends up in error
* createOrReplace: if the _id already exists, the request embedded document will replace the existing one

There are several cases where a `createOrUpdate` strategy is needed

**Comment by ballinette** [comment]
@scottinet do we have concrete use case for this need ?
do we put the issue into the backlog, or let it into the icebox for now ?

**Comment by scottinet** [comment]
oh, old one

IIRC it was a question asked by a client?

I do see how a "create or update" route might be a better option than a "create or replace" one, but I think this is circumstancial, and probably caused by poor document concurrency design to begin with.

So, regarding your question: neither in the backlog nor in the icebox, I vote for a close.

**Comment by ballinette** [comment]
OK.
We can anyway reopen it in the future if necessary
