### ISSUE TITLE
security:searchRole ignore roles using wildcarded controllers

### ISSUE THREAD

**Issue by scottinet** [kuzzleio/kuzzle#679]
The `security:searchRole` API route searches all roles related to a provided list of controllers.
As such, roles applied to all controllers (using a wildcard) should always be returned. Currently, they are ignored by the API route.

**Comment by ballinette** [comment]
OK, it's not only the wildcarded controllers, but ALL roles that cannot be searched.
Because within the `role` mapping in the internal index, the `controllers` attribute is not searchable.

**Comment by ballinette** [comment]
I've found a workaround with the elasticsearch mapping for roles, but really not fan of it... let's discuss about it tomorrow

**Comment by ballinette** [comment]
Finally fixed with another approach : we fetch all roles from ElasticSearch, and then apply filters on the list (see #684 )
