### ISSUE TITLE
getElasticsearchRequest in elasticsearch service should only return useful argument for the current request action

### ISSUE THREAD

**Issue by dbengsch** [kuzzleio/kuzzle#682]
When it is called with extra parameters, they are all transmitted to the elasticsearch request, even if they are not useful (and potentially make the request fail). `['from', 'size', 'scroll', 'scrollId', 'refresh']` should only be transmitted to the request when they are useful.

**Comment by xbill82** [comment]
@dbengsch Isn't this already implemented?
https://github.com/kuzzleio/kuzzle/blob/master/lib/services/elasticsearch.js#L984
