### ISSUE TITLE
Migrate SHA-1 function to SHA-256

### ISSUE THREAD

**Issue by stafyniaksacha** [kuzzleio/kuzzle#691]
As google as reported, SHA-1 must not be used anymore as hashing function.

Migrate JWT token hash function by something more secure

**Comment by ballinette** [comment]
Hi, can you give an explanation (link ?) more explicit than "As google has reported" ?

**Comment by ballinette** [comment]
anyway, we already use a SHA-256 algorithm for JWT tokens: 
https://github.com/kuzzleio/kuzzle/blob/master/default.config.js#L47

**Comment by gandbox** [comment]
Done
