### ISSUE TITLE
Remove PluginImplementationError from the diagtools whitelist

### ISSUE THREAD

**Issue by scottinet** [kuzzleio/kuzzle#716]
Currently, when diagtools are activated (which is the default), Kuzzle creates automatically a dump directory each time a plugin throws an error.

Since we (usually) don't provide support for plugins and that, depending on code quality, these plugins might throw often, creating a dump systematically is 1/ counterproductive and 2/ dangerous as too many coredumps fill up disk space quickly.

**Comment by gandbox** [comment]
@scottinet Done ? QA ?

**Comment by scottinet** [comment]
Done.
