### ISSUE TITLE
Do not generate core dump when elasticsearch raise unmanaged errors

### ISSUE THREAD

**Issue by stafyniaksacha** [kuzzleio/kuzzle#731]
Today we [generate a standard `Error` object](https://github.com/kuzzleio/kuzzle/blob/master/lib/services/elasticsearch.js#L944) when we get unmanaged error from elasticsearch, which cause Kuzzle to crash.

We have to implement a new error type in [kuzzle-common-objects](https://github.com/kuzzleio/kuzzle-common-objects) to handle this kind of errors (eg: `ExternalServiceError`)

**Comment by scottinet** [comment]
Requalified this issue, as generating standard Error objects does not cause a crash.
It only causes a dump generation with default diagtools settings, which might fill up disk space if these kind of errors occur too frequently.
