### ISSUE TITLE
Kuzzle install doesn't work on Debian Wheezy amd64 with nodeJS 6

### ISSUE THREAD

**Issue by neolas** [kuzzleio/kuzzle#789]
Kuzzle install fail when the installer try to install **dumpme** package.
I install gdb package on system but it doesn't work.

> make: Entering directory `/home/site/kuzzle/node_modules/dumpme/build'
>   CXX(target) Release/obj.target/dumpme/lib/dumpme.o
> In file included from ../../nan/nan.h:2316:0,
>                  from ../lib/dumpme.cc:3:
> ../../nan/nan_json.h: In member function 'Nan::MaybeLocal<v8::Value> Nan::JSON::Parse(v8::Local<v8::String>)':
> ../../nan/nan_json.h:87:52: warning: 'static v8::Local<v8::Value> v8::JSON::Parse(v8::Local<v8::String>)' is deprecated (declared at /home/site/.node-gyp/6.10.2/include/node/v8.h:1681): Use maybe version [-Wdeprecated-declarations]
> ../lib/dumpme.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE dumpProcess(Nan::NAN_METHOD_ARGS_TYPE)':
> ../lib/dumpme.cc:29:13: error: 'PR_SET_PTRACER' was not declared in this scope
> ../lib/dumpme.cc:29:29: error: 'PR_SET_PTRACER_ANY' was not declared in this scope
> ../lib/dumpme.cc:51:13: error: 'PR_SET_PTRACER' was not declared in this scope
> make: *** [Release/obj.target/dumpme/lib/dumpme.o] Error 1
> make: Leaving directory `/home/site/kuzzle/node_modules/dumpme/build'
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> gyp ERR! System Linux 2.6.32-23-pve
> gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/site/kuzzle/node_modules/dumpme
> gyp ERR! node -v v6.10.2
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm ERR! Linux 2.6.32-23-pve
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
> npm ERR! node v6.10.2
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> 
> npm ERR! dumpme@1.0.0 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the dumpme@1.0.0 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the dumpme package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs dumpme
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls dumpme
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/site/kuzzle/npm-debug.log

NodeJS : v6.10.2
Debian : 7.11
System : Linux kuzzle 2.6.32-23-pve #1 SMP Tue Aug 6 07:04:06 CEST 2013 x86_64 GNU/Linux

Note  : no problem on Debian 8 / NodeJS 7

**Comment by ballinette** [comment]
Hi @scottinet 
I've reproduced it on debian wheezy.
I suggest to close this issue as "won't fix", while wheezy is now obsolete for a few years, and it works in Jessie... unless you want to put an eye it and fix backward compatibilities with old kernels on `dumpme` package ?

**Comment by scottinet** [comment]
Well, I think it's better to add a fallback for older kernels without Yama. I'll fix this during the week.

**Comment by scottinet** [comment]
This should solve the issue: https://github.com/kuzzleio/dumpme/pull/1
