### ISSUE TITLE
Add more option to the "reset" CLI command 

### ISSUE THREAD

**Issue by scottinet** [kuzzleio/kuzzle#818]
The `bin/kuzzle reset` command currently wipe all kuzzle internal data (both in ES and in redis).

While this is useful, the recent addition of plugins CRUDL triggers the need for more control over what part(s) of Kuzzle need to be reset.

Proposal:

* `bin/kuzzle reset` shows the command help, instead of triggering the reset
* new options are added to the reset command:
  * `--kuzzle`: wipe all kuzzle data (current behavior)
  * `--plugins`: wipe all plugins data
  * `--plugin <plugin name>`: wipe `<plugin name>` data
  * `--appdata`: wipe ES and Redis non-kuzzle non-plugins data

The idea is to force CLI users to describe explicitly what parts of Kuzzle are to be reset, while giving more control compared to the current implementation.

Options should be additive. For instance, passing `--kuzzle --plugins` will wipe all kuzzle and plugins data.

The command help should also explain that passing `--kuzzle --plugins --appdata` will wipe the entire storage (both cache and database), to make clear to any admin that there won't be leftovers once the command has been processed.

**Comment by ballinette** [comment]
Issue moved to [kuzzleio/kuzzle-backlog #191](https://github.com/kuzzleio/kuzzle-backlog/issues/191) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ballinette** [comment]
Issue moved to [kuzzleio/kuzzle-backlog #190](https://github.com/kuzzleio/kuzzle-backlog/issues/190) via [**ZenHub**](https://www.zenhub.com/)
