### ISSUE TITLE
Login and Logout should not be GET methods

### ISSUE THREAD

**Issue by dbengsch** [kuzzleio/kuzzle#831]
Currently one of login's route and the logout route are GET methods in HTTP:

```
  {verb: 'get', url: '/_login/:strategy', controller: 'auth', action: 'login'},
  {verb: 'get', url: '/_logout', controller: 'auth', action: 'logout'},
```

Both should (only) be POST methods.

By the way the login routes where strategy is provided in the url don't work at the moment.
After discussion, only the POST route without strategy in the url should be kept, but the body structure should be adapted to something like:
```json
{
  "local": {
    "username": "MyUser",
    "password": "MyPassword"
  },
  "anotherStrategy": {...}
}

**Comment by ballinette** [comment]
:warning:  We need the get method for `login` action, as oauth plugin though passport.js use it: when the user is authenticated in the remote identity provider, he is redirected to Kuzzle's login action through a HTTP GET request containing the oauth token in the query-string.
