### ISSUE TITLE
Implement ES Search After

### ISSUE THREAD

**Issue by benoitvidis** [kuzzleio/kuzzle#856]
Scroll are good but require ES to keep a context in memory, which comes at a cost.

Since ES 5.x, the [Search After](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-after.html) provides an additional effective way to retrieve a deeply paged collection.

In contexts where a large number of concurrent requests need to display a large number of documents each, this is a far better alternative to the scroll api.

**Comment by samniisan** [comment]
Looks like it's already working on Kuzzle & API side without any modification.

We should update the documentation on search routes and probably advice end users to use this method to fetch big volume of documents instead of using scroll methods.
