### ISSUE TITLE
Cannot sort on search

### ISSUE THREAD

**Issue by benoitvidis** [kuzzleio/kuzzle#868]
ES javascript allows to set the sort at the same level as `from` and `size`, but Kuzzle does not.

In other words:
```javacript
req = {
  body: {},
  sort: [
    {field1: 'asc'},
    {field2: 'desc'}
  ]
```
**does not work** 

```javascript
req = {
  body: {
    query: {
      match_all: {}
    },
    sort: [
       {field1: 'asc'},
      {field2: 'desc'}
    ]
  }
```
works.

May be worth considering other parameters as well, i.e. suggestxx ones

To be discussed on if Kuzzle should implement it as args but even if we decide not to, we should clearly document how to sort.

**Comment by ballinette** [comment]
in a more general discussion, we could handle any querystring parameters acceptable for ElasticSearch as input.args in Kuzzle. see https://www.elastic.co/guide/en/elasticsearch/reference/5.x/search-uri-request.html

Point to discuss: Elastic provides 2 ways to inject some of there parameters: in root args (ie. querystring in the HTTP request), or in the request body.
How do we manage the possible conflicts btw; this 2 ways ?
example:
```javascript
req = {
  body: {
    query: { match_all: {} },
    sort: [
      {field1: 'asc'},
      {field2: 'desc'}
    ],
    from: 0,
    to: 20
  },
  sort: [
    {field2: 'asc'},
    {field1: 'desc'}
  ],
  from: 12,
  to: 57
}
```

**Comment by scottinet** [comment]
Largely outdated: sort and aggs have been accepted parameters for a long time now.
