### ISSUE TITLE
How is the volatile information handled in HTTP

### ISSUE THREAD

**Issue by dbengsch** [kuzzleio/kuzzle#871]
Discuss about how we can handle volatile information in HTTP

**Comment by xbill82** [comment]
Coud you please define "volatile information"?

**Comment by ballinette** [comment]
@xbill82 see here: http://docs.kuzzle.io/api-documentation/volatile-data/

Indeed, volatiles can ben send with websocket protocol, but not with HTTP for now, and actually, this block this issue for PHP SDK: https://github.com/kuzzleio/kuzzle-sdk/issues/35

**Comment by ballinette** [comment]
The "less bad" solution I've found is to includes volatile data within the Request's body, and then let the HTTP Router Handler move the to the root of `request.input` object.

A client"s request would be like that:
```
curl -X POST -H "Content-Type: application/json"  http://kuzzle:7512/<index>/<collection>/<documentId>/_update
{
  "somefield": "now has a new value",
  "someOtherField": "another value",
  "_volatile": {
    "modifiedBy": "awesome me",
    "reason": "it needed to be modified"
  }
}
```
And while parsing the input HTTP request to create the Kuzzle request object, the `RouteHandler` will move `_volatile` data to `request.input.volatile` (and keep other attributes to `request.input.body` of course)

Any other suggestions ?

**Comment by ballinette** [comment]
thx to @scottinet , a better suggestion: use the http headers, with the stringified `volatile` json object
we can name it `X-Kuzzle-Volatile`, for example.
