### ISSUE TITLE
Uri differs between route with/without leading slash 

### ISSUE THREAD

**Issue by stafyniaksacha** [kuzzleio/kuzzle#883]
When registering route with plugins like: 
```js
this.routes = [
  {verb: 'get', url: '/do-something', controller: 'myNewController', action: 'myNewAction'}
];
```

Call: 
- `http://<kuzzle server>:<port>/_plugin/<plugin>/do-something` -> `200` OK
- `http://<kuzzle server>:<port>/_plugin/<plugin>/do-something/` -> `404` KO

**Comment by ballinette** [comment]
not only for route plugins, it's also the case for core routes.
