### ISSUE TITLE
Add a missing profile to user with backoffice

### ISSUE THREAD

**Issue by BaptisteKaliop** [kuzzleio/kuzzle#887]
Kuzzle version : commit 586bb1677b1f01619806534004bad32a8d5641be

I added a not existent profile to a user.

Then when I tried to go back to the backoffice, I have the error : 
`(404) Unable to hydrate the user 6b1ed53a-cc45-4b84-a3ce-cd7a9f71c356. The following profiles don't exist: BoProfile`

So I removed this profile from ElasticSearch then reload Kuzzle and I still can't connect to the backoffice

**Comment by BaptisteKaliop** [comment]
@ballinette's advice was to use the bin/kuzzle clearCache and that solved my issue

**Comment by ballinette** [comment]
The `clearCache` command enables to empty the cache, and get back to a working user...

... but the origin bug (inconsistent data if we try to create/update a user with a bad profile) is still to fix.

**Comment by xbill82** [comment]
@ballinette I'm trying to reproduce,

**Comment by xbill82** [comment]
Well, it turns out that, via the BO, it is not possible to update an existing user with a non existing profile. But it _is_ possible via the barebone SDK, which actually breaks the BO.
Though this bug is still relevant.

**Comment by BaptisteKaliop** [comment]
Well with : http://kuzzle-backoffice-comexposium.netlify.com/#/security/users
On commit : 586bb1677b1f01619806534004bad32a8d5641be.

This is still a thing.

Dunno if v1 fix the issue or the issue is in the SDK

**Comment by xbill82** [comment]
@scottinet  is taking care of this in #893
