### ISSUE TITLE
Problem with custom expiresIn duration in login function

### ISSUE THREAD

**Issue by AnthonySendra** [kuzzleio/kuzzle#904]
Hello,

In BO, when we set a custom `expiresIn` in function `kuzzle.loginPromise("local", {username: "username", password: "password"}, expiresIn)` Kuzzle ignores this option.

The problem comes from Kuzzle (or maybe from method login in sdk?): in `authController:login` we try to get the `expiresIn` in `request.input.args` (https://github.com/kuzzleio/kuzzle/blob/1.x/lib/api/controllers/authController.js#L101) but I find it in `request.input.body.expiresIn`

**Comment by ballinette** [comment]
My opinion is that `expiresIn` should be place in `args` (as it is actually done in Kuzzle side), and we should fix both SDK and documentation to follow that.

Do everybody agree with that ?

**Comment by ballinette** [comment]
Note: `expiresIn` has been moved from `input.body` to `input.args`by #845 
We forgot to update documentation and SDKs following that.

**Comment by ballinette** [comment]
Issue moved to [kuzzleio/kuzzle-sdk #39](https://github.com/kuzzleio/kuzzle-sdk/issues/39) via [**ZenHub**](https://www.zenhub.com/)
