### ISSUE TITLE
Timeout is not really a timeout

### ISSUE THREAD

**Issue by BaptisteKaliop** [kuzzleio/kuzzle#920]
As seen with @AnthonySendra , the timeout in Kuzzle is not really a timeout since requests are still being processed 

Basically, setup a plugin Controller that do a setTimeout for 15 seconds and console.log something after, the kuzzle proxy will answer a 500 "backend too long to respond". But the pm2 logs show what you logged after 15 secs, meaning that the request has not been discarded really.

This can lead to overloaded Kuzzle because the stack of requests is filling up

**Comment by ballinette** [comment]
As discussed with @benoitvidis while refactoring entry points, we have planed to remove the timeouts feature. 
See https://github.com/kuzzleio/kuzzle/pull/917
