### ISSUE TITLE
es config - default host entry superseeds hosts

### ISSUE THREAD

**Issue by benoitvidis** [kuzzleio/kuzzle#926]
When trying to configure the elasticsearch endpoint to a cluster, the `hosts` constructor option is ignored in favour or the default `host`. 
As a workaround, setting the `host` param to falsy works but is a little too hacky

```json
{
  "services": {
    "db": {
      "client": {
        "host": null,
        "hosts": [
          {"host": "10.253.32.98", "port": "9200"}
        ]
      }
    }
}
```

**Comment by scottinet** [comment]
How do we choose which one to use when both options are set?

I think we should remove the `host` option in favor of the `hosts` one. To me, if we want to configure only 1 host, then we should only add one object to the hosts list.

**Comment by benoitvidis** [comment]
Actually, I was incorrect in the issue presentation. The problem is not using `host` vs `hosts`, it is more in having a `client` entry set by default in the configuration, which superseeds former deprecated.

Anyway, since we've published a couple of releases and the older format is clearly marked as not being supported on the switch to 1.0, I just cleaned old traces from the code.
