### ISSUE TITLE
support of ES index aliases

### ISSUE THREAD

**Issue by ballinette** [kuzzleio/kuzzle#949]
Add methods to create/delete aliases
see. https://www.elastic.co/guide/en/elasticsearch/reference/5.5/indices-aliases.html

**Comment by Aschen** [comment]
Partial support: https://github.com/kuzzleio/kuzzle/pull/1231
Kuzzle can use ES aliases as traditional indexes but they have to be created with ES api

**Comment by scottinet** [comment]
We probably will never add full support as we don't aim at having es as our only storage engine available
