### ISSUE TITLE
Install's script never finish but kuzzle is up and running

### ISSUE THREAD

**Issue by BaptisteKaliop** [kuzzleio/kuzzle#953]
I just downloaded and execute 
`sudo bash -c "$(curl http://get.kuzzle.io/)"`

Here is the output : 
# Kuzzle Setup 
   ============ 

 This script will help you launching Kuzzle and installing 
 all the necessary dependencies. 

 * You can refer to http://docs.kuzzle.io/ if you need better 
   understanding of the installation process. 
 * Feel free to join us on Gitter at https://gitter.im/kuzzleio/kuzzle 
   if you need help. 

 Press Enter to start. 

 [ℹ] Checking system pre-requisites... 

 [✔] Architecture is x86_64. 
 [✔] Available memory is at least 4Gb. 
 [✔] Script has root privileges. 
 [✔] cUrl is installed. 
 [✔] Docker is installed and running. 
 [✔] Docker Compose is installed. 
 [✔] vm.max_map_count is at least 262144. 

 [✔] All the requirements are met! 
     We are ready to install and start Kuzzle. 

 [ℹ] Downloading Kuzzle launch file... 
 [✔] The Kuzzle launch file has been successfully downloaded. 

     This script can launch Kuzzle automatically or you can do it 
     manually using Docker Compose. 
     To manually launch Kuzzle you can type the following command: 
     docker-compose -f /home/gara/.kuzzle/docker-compose.yml up 

 [❓] Do you want to pull the latest version of Kuzzle now? (y/N) 
     If you never have started kuzzle, it will be pulled automatically 
> y

 [ℹ] Pulling latest version Kuzzle... 
 [✔] Done. 

 [❓] Do you want to automatically start Kuzzle now? (y/N)  
> y

 [ℹ] Starting Kuzzle... 
 [ℹ] Checking that everything is running 
................................................................................................................................................................................................................................................................................................................................................................................[...]....

I checked http://localhost:7512/ and  I had the normal output response : 

{"requestId":"148696a3-40b3-489c-a1c6-f306bf9386d8","status":200,"error":null,"controller":"server","action":"info","collection":null,"index":null,"volatile":null,"result":{"serverInfo":{"kuzzle":{"version":"1.2.0","api":{"routes":{"auth":{"logout":{"controller":"auth","action":"logout","http":{"url":"/_logout","verb":"POST"}},"login":{"controller":"auth","action":"login","http":{"url":"/_login/:strategy","verb":"GET"}},"getCurrentUser":
........}

The script keep running after 10 min.

**Comment by ballinette** [comment]
Hi.
I'm not able to reproduce it

Can you give us more info about your environment ?

**Comment by BaptisteKaliop** [comment]
What do you want?

**Comment by ballinette** [comment]
which linux distribution you have, which shell.

And you're at the final step, and http://localhost:7512 give you the correct response, try following commands and tell me the result:

```
curl -f -s -o /dev/null "http://localhost:7512"
echo $?
````

**Comment by BaptisteKaliop** [comment]
xubuntu 16.04, with Bash

Directly after [ℹ] Checking that everything is running
I execute your commands :  
- The first time I got 6
- then after, i always got 0

**Comment by ballinette** [comment]
Can you try with this script ?

[kuzzle-install.sh.zip](https://github.com/kuzzleio/kuzzle/files/1266478/kuzzle-install.sh.zip)

**Comment by BaptisteKaliop** [comment]
[❓] Do you want to automatically start Kuzzle now? (y/N)  
> y

 [ℹ] Starting Kuzzle... 
 [ℹ] Checking that everything is running 
0
6
6
6
6
6
6
6
6
6
6


Kuzzle is up and running

**Comment by ballinette** [comment]
hmm. and with this one ? (more verbose outputs)
[kuzzle-install.sh.zip](https://github.com/kuzzleio/kuzzle/files/1266560/kuzzle-install.sh.zip)

**Comment by BaptisteKaliop** [comment]
Well looks like an issue with missing lcoalhost in my hosts.

**Comment by BaptisteKaliop** [comment]
[ℹ] Checking that everything is running 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: localhost
6

**Comment by BaptisteKaliop** [comment]
Actually, it would not be more reliable to curl on 127.0.0.1?

**Comment by BaptisteKaliop** [comment]
I just fixed the issue by adding 127.0.0.1 localhost in my etc/hosts.
