### ISSUE TITLE
security create/update user methods - Split content from profile ids

### ISSUE THREAD

**Issue by benoitvidis** [kuzzleio/kuzzle#986]
For the time being, security.createUser expects the body to look like
```
{
  content: {
    foo: 'bar'
  },
  profileIds: ['profile1', 'profile2'],
  credentials: {
    strategy: { [..] },
  }
}
```

while update & replace methods expect a flat object, mixing the content and a reserved member 'profileIds': 
```
{ 
  foo: 'bar',
  profileIds: ['profile1', 'profile2']
}
```

This behaviour is not consistent and can lead to some confusion.
All these methods should take split arguments.

NB: This may imply some breaking changes on the API. @tbd on how / when to implement it

**Comment by ballinette** [comment]
Added to backlog

**Comment by Aschen** [comment]
Too old.
