### ISSUE TITLE
Check Node 8 compatibility (new LTS version)

### ISSUE THREAD

**Issue by dbengsch** [kuzzleio/kuzzle#995]
It could be good to test Kuzzle with the new LTS version of Node.js.
A side question is to discuss about how we deal with recommended version of node in Kuzzle in general.

**Comment by scottinet** [comment]
In my opinion, a product's minimum requirements must remain the same during the entire duration of a major version. Dropping a min. requirement would be a breaking change.

This means that while we must make sure that Kuzzle is compatible with Node.js v8, we can only do so if that doesn't make it incompatible with Node.js v6.
Regarding Node.js I think that this won't be a problem, but that may not be the case with other requirements (e.g. Elasticsearch)

**Comment by dbengsch** [comment]
I think you are absolutely right. We have to stay compatible with our minimal requirements. We could argue that is might be less important when the nodejs version is no longer supported; for node 6, it will end in "April 2019". For now if we can make both 6 and 8 versions compatible it would be great.

**Comment by scottinet** [comment]
kuzzle now fully supports node 6 a 8
Node.js 8 is the default version in our docker containers.
