### ISSUE TITLE
document.create should check index existence in ElasticSearch if not present in indexCache

### ISSUE THREAD

**Issue by ballinette** [kuzzleio/kuzzle#996]
here: 
https://github.com/kuzzleio/kuzzle/blob/master/lib/services/elasticsearch.js#L276

If an index has been created directly into Elastic Search without passing through Kuzzle, it won't be added to Kuzzle's `indexCache`.
Thus, if we try to create a document, we have a `PreconditionError`, whereas the index actually exists.

To avoid that, we need to check the index existence into the cache, and if not present, call elasticsearch and refresh the cache.

**Comment by Aschen** [comment]
Fixed by https://github.com/kuzzleio/kuzzle/pull/1119
