### ISSUE TITLE
request.context.user.isActionAllowed not usable in plugin context

### ISSUE THREAD

**Issue by dbengsch** [kuzzleio/kuzzle#997]
The method `request.context.user.isActionAllowed` is not usable in the plugin context as it needs a kuzzle instance as second parameter; as it is accessible in the Request, it might be good to provide a way to call it properly

**Comment by ballinette** [comment]
we should remove the closure mechanism to break the dependency to Kuzzle instance.

**Comment by benoitvidis** [comment]
@ballinette The problem also occurs with `user.getRights` & `user.getProfiles`.
Other problem: do we consider touching the signature of these methods is a breaking change?... (IMO, we can live with it).

Finally, we need to make care not to inject kuzzle as a public property of the user object.

I'll check what can be done here (as a first lead, I am thinking of injecting these methods by the repository during the hydratation)
